### ISSUE TITLE
Pack Untilize gives bad PCC when block_ct_dim < full_ct_dim

### ISSUE THREAD

**Issue by yugaoTT** [tenstorrent/tt-metal#11573]
**Describe the bug**
for Conv unit test, block_ct_dim=1, full_ct_dim = 2, pack_untilize gives garbage PCC, when set block_ct_dim= full_ct_dim=2, PCC is good.

**To Reproduce**
1. Go to `yugao/pack_untilize`
2. Run 
3. To get rid of the PCC error, comment out the hard-coded `out_subblock_h_ntiles = 1; out_subblock_w_ntiles = 1; ` in 
    `ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp`

**Comment by yugaoTT** [comment]
fyi @mywoodstock

**Comment by cmaryanTT** [comment]
Marking as P2, this hasn't come up as an issue during the generality push.

@mywoodstock - consider re-evaluating this one to see if it's still relevant at all.

**Comment by prajaramanTT** [comment]
@yugaoTT Is this still an open issue ? If not, can you please mark this closed ? Thanks.

**Comment by yugaoTT** [comment]
@prajaramanTT I need to double check, I don't recall this issue being resolved though

**Comment by yugaoTT** [comment]
I cannot make the conv test working now that a lot has been changed in conv, so I made a new test that fails with pack_untilize in yugao/pack_untilize2.

I tried a pack_untilize test, and seems still failing with block_ct_dim=4,full_ct_dim=8

the changes are in ttnn/cpp/ttnn/operations/data_movement/untilize/device/kernels/compute/pack_untilize.cpp

@ttmtrajkovic @mywoodstock the pack_untilize_block doesn't seem to iterate over full_ct_dim, but only iterate block_ct_dim.

**Comment by rtawfik01** [comment]
Hi @yugaoTT, there is an open bug that full_ct_dim != block_ct_dim does not work currently in the LLKs, there is a mention of it here: https://github.com/tenstorrent/tt-metal/issues/11716

If this issue becomes higher priority then the LLK team can work on fixing this issue for pack_untilize, please let us know.

**Comment by yugaoTT** [comment]
@rtawfik01 thanks for the update, no there's no priority uplift

**Comment by yugaoTT** [comment]
is there update on this issue? @llongTT is adding pack untilize support to matmul and potentially hitting this issue after some shape.

**Comment by yugaoTT** [comment]
@pmilenkovicTT thanks! I see in your branch it is testing pack_untilize_block, In our matmul kernels we are using pack_untilize_dst, would that also be fixed by the same PR?

**Comment by pmilenkovicTT** [comment]
Hey @yugaoTT, the changes for both WH and BH for pack_untilize are integrated in the LLK - feel free to test them out, and let me know if you think there's something more to do, or we could close the issue. 

Note: `tests/tt_metal/tt_metal/test_kernels/compute/pack_untilize.cpp` contains the proposed solution for writing kernels with the new pack_untilize - this solution was tested with various inputs.

**Comment by avoraTT** [comment]
Still seeing some bad PCC for some cases.

### Repro steps:
- Machine: n150 w/ `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml`
- Commit: `b798230b40e142f18fb6c12d341b763437555cb7`
- Command: `pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_mla_ops.py -k update_cach`


### Specs
- `num_blocks_per_col: 3`
- `block_ct_dim: 6`
- `full_ct_dim: 18`
- dtype: bfloat16

**Comment by pmilenkovicTT** [comment]
Hey @avoraTT, I am not able to reproduce the issue, as I get the following error:

```
______________________________________________________________________ ERROR collecting tests/tt_eager/python_api_testing/unit_testing/misc/test_mla_ops.py ______________________________________________________________________
ImportError while importing test module '/localdev/pmilenkovic/tt-metal/tests/tt_eager/python_api_testing/unit_testing/misc/test_mla_ops.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
python_env/lib/python3.10/site-packages/_pytest/python.py:618: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
python_env/lib/python3.10/site-packages/_pytest/pathlib.py:506: in import_path
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
python_env/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
tests/tt_eager/python_api_testing/unit_testing/misc/test_mla_ops.py:23: in <module>
    from models.demos.deepseek_v3_impl.model import (
models/demos/deepseek_v3_impl/model.py:10: in <module>
    from .kernel import act_quant, fp8_gemm, weight_dequant
models/demos/deepseek_v3_impl/kernel.py:4: in <module>
    import triton
E   ModuleNotFoundError: No module named 'triton'
```

However, I wanted to test out the algorithm with your parameters, and I get the passing cpp test with the following parameters:
`0:(x=0,y=0):TR0: block_ct_dim: 6, full_ct_dim: 18, num_blocks_per_col: 3, per_core_block_cnt: 1`

I modified `TensixComputeUnpackTilize` in test_untilize_tilize.cpp to accept 18 tiles, which checks the input and output vectors in the following way: 
```
    pass &= (golden.size() == result_vec.size());
    pass &= (golden == result_vec);
```

**Comment by avoraTT** [comment]
Sorry, you can `pip install triton==3.0.0` to get past that error.

Does that mean that you were able to get a passing test without any changes in the backend?

**Comment by pmilenkovicTT** [comment]
Trying it out right now - yes, I didn't change anything in the LLK code, it is a unit test for pack_utilize that is passing.

**Comment by pmilenkovicTT** [comment]
Resolved it with @avoraTT offline, the issue was improper usage of `pack_untilize_block` - no LLK changes necessary.

**Comment by pmilenkovicTT** [comment]
@yugaoTT Sorry to write again - is there anything else regarding this issue that is required, or could we close it?

**Comment by yugaoTT** [comment]
Thanks @pmilenkovicTT, talked to @avoraTT offline, think we can close now.
