### ISSUE TITLE
Facing shape mismatch issue with conv in MobilenetV2

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#12141]
**Describe the bug**
Facing `The width of the first tensor must be equal to the height of the second tensor.` with conv in MobilenetV2 unit test cases.

**To Reproduce**
1. Checkout [keerthanar/mobilenetv2_unittest_cases](https://github.com/tenstorrent/tt-metal/tree/keerthanar/mobilenetv2_unittest_cases)
2. Run `pytest tests/ttnn/unit_tests/operations/test_new_conv2d.py::test_conv_mobilenetv2_matmul_issue`

**Please complete the following environment information:**
- WH n150

**Comment by sankarmanoj-tt** [comment]
This bug has been fixed in the [`smanoj/segformer_bias_fix`](https://github.com/tenstorrent/tt-metal/tree/smanoj/segformer_bias_fix) branch

**Comment by keerthana-r-mcw** [comment]
Hi @sankarmanoj-tt ,
I checkedout [smanoj/segformer_bias_fix](https://github.com/tenstorrent/tt-metal/tree/smanoj/segformer_bias_fix) branch, and tried running the test. But the error persists.

**Comment by sankarmanoj-tt** [comment]
Did you rebuild after checking out the branch?

**Comment by keerthana-r-mcw** [comment]
Yes, I rebuilt the repo after checking out the branch.

**Comment by dvartaniansTT** [comment]
@keerthana-r-mcw doesn't look like this issue is resolved! why is it closed?

**Comment by sankarmanoj-tt** [comment]
@keerthana-r-mcw Please checkout this branch and try. [smanoj/fix_matmul_validation](https://github.com/tenstorrent/tt-metal/tree/smanoj/fix_matmul_validation)

**Comment by keerthana-r-mcw** [comment]
Hi @sankarmanoj-tt , The test is working with this branch.
Thanks!

**Comment by bbradelTT** [comment]
@keerthana-r-mcw @sankarmanoj-tt the error message is there for a reason. There are corner cases where the output may be incorrect if the assertion is not satisfied.

You need to change the model or underlying conv code to make the shapes line up.
