### ISSUE TITLE
ttnn.reshape segfaults or gets stuck on some shapes after some time executing in a sweep

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#14515]
ttnn.reshape segfaults or gets stuck on some shapes after some time executing in a sweep

```
input_shape [38, 14] rehape_shape [19, 28] input_a_dtype DataType.BFLOAT8_B
Segmentation fault (core dumped)
```

 * Steps to reproduce

Checkout main branch.

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/data_movement/reshape/reshape.py`. To run:

```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name data_movement.reshape.reshape
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name data_movement.reshape.reshape
```

After some time sweep will segfault or it will get stuck.

**Comment by jvegaTT** [comment]
Solved in this pr https://github.com/tenstorrent/tt-metal/pull/15572

**Comment by jvegaTT** [comment]
Should be resolved now

**Comment by nemanjagrujic** [comment]
@jvegaTT Reopening this, sweep test still gets stuck on my WH n150. You can run sweep test with:

```
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name data_movement.reshape.reshape
```

To check.

**Comment by jvegaTT** [comment]
My appologies, I was using a different sweep for reshape which didn't include for some reason any bfloat8_b shapes. It appears the problem is only with this datatype. The problem is reshape operates on row major with a utilize and tilize op but bfloat8_b is not supported by row major. I will need to investigate a bit to see how to support this

**Comment by jvegaTT** [comment]
It looks like the above sweep was also including invalid shapes for bfloat8_b. A TT_FATAL was added to catch invalid bfloat8_b shapes. For guidance we currently only support bfloat8_b with no padding.

We are currently modifying the reshape.reshape sweep to operate on bfloat16 and float32 that work with every shape as this particular sweep uses randomization to make their shapes.

**Comment by nemanjagrujic** [comment]
> It looks like the above sweep was also including invalid shapes for bfloat8_b. A TT_FATAL was added to catch invalid bfloat8_b shapes. For guidance we currently only support bfloat8_b with no padding.
> 
> We are currently modifying the reshape.reshape sweep to operate on bfloat16 and float32 that work with every shape as this particular sweep uses randomization to make their shapes.

After adding TT_FATAL we don't observe hang or segfault anymore, at least few times that I tested.

**Comment by jvegaTT** [comment]
Can the issue be closed then?

**Comment by nemanjagrujic** [comment]
> Can the issue be closed then?

Yes
