### ISSUE TITLE
ttnn.reshape with bfloat8_b input on some shapes gives low PCC 

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#14513]
ttnn.reshape with bfloat8_b input on some shapes gives low PCC. Interesting is that on some shapes we are getting good pcc. For instance:

```
input_shape [5, 4, 208, 156] rehape_shape [3, 13, 8, 2080] input_a_dtype DataType.BFLOAT8_B
PCC = -0.0015951839508086992
```

 * Steps to reproduce

Checkout main branch.

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/data_movement/reshape/reshape.py`. To run:

```
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name data_movement.reshape.reshape
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by jvegaTT** [comment]
Issue is resolved in PR https://github.com/tenstorrent/tt-metal/pull/15572, the above test was proven to pass and added to the pytest script

**Comment by jvegaTT** [comment]
Should be resolved now

**Comment by nemanjagrujic** [comment]
@jvegaTT Still happening with latest main on my WH n150. In file `tests/sweep_framework/sweeps/data_movement/reshape/reshape.py` on line 138 you can uncomment `print(pcc)` and run sweep with:

```
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name data_movement.reshape.reshape
```

You will see low PCC.

**Comment by jvegaTT** [comment]
So according to this document https://docs.tenstorrent.com/ttnn/latest/ttnn/tensor.html ttnn only supports widths for bfloat8_b that are multiple of 32 for tiled. I just verified however and it seems the typecast function only supports unpadded tiles in general so the last two dimensions have to be multiples of 32. Otherwise I am seeing erroneous behaviour with padded tiles.

**Comment by jvegaTT** [comment]
And my apologies on closing it, it seems I was running a different reshape sweep that doesn't have bfloat8 in it

**Comment by nemanjagrujic** [comment]
> And my apologies on closing it, it seems I was running a different reshape sweep that doesn't have bfloat8 in it

Not a problem!

**Comment by jvegaTT** [comment]
The above unsupported shape now causes the TT_FATAL assertion "illegal dimensions for a bfloat8 tensor" as this shape has padding which makes it incompatible with bfloat8_b (currently only works on unpadded shapes). A separate issue and discussion should be raised if we want to remove that requirement which would require a significant effort to many of the operations. For now though I am closing this issue as it asserts out as expected.
