### ISSUE TITLE
Need support for item assignment operation in ttnn.tensor

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#15553]
**Describe the bug**
Need support for item assignment operation in ttnn.tensor.

**To Reproduce**
1. Run the following code
```
@pytest.mark.parametrize("device_params", [{"l1_small_size": 24576}], indirect=True)
def test(device):
    tmp=torch.randn(1, 900, 10)
    reference=torch.randn(1, 900, 3)
    ttnn_tmp=ttnn.from_torch(tmp,layout=ttnn.TILE_LAYOUT,device=device)
    ttnn_reference=ttnn.from_torch(reference,layout=ttnn.TILE_LAYOUT,device=device)

    ttnn_tmp[..., 0:2] += ttnn_reference[..., 0:2]

```
**Expected behavior**
To assign value to the tensor without any issue

**Screenshots**
```
    @pytest.mark.parametrize("device_params", [{"l1_small_size": 24576}], indirect=True)
    def test(device):
        tmp=torch.randn(1, 900, 10)
        reference=torch.randn(1, 900, 3)
        ttnn_tmp=ttnn.from_torch(tmp,layout=ttnn.TILE_LAYOUT,device=device)
        ttnn_reference=ttnn.from_torch(reference,layout=ttnn.TILE_LAYOUT,device=device)
    
>       ttnn_tmp[..., 0:2] += ttnn_reference[..., 0:2]
E       TypeError: 'ttnn._ttnn.tensor.Tensor' object does not support item assignment
```

**Please complete the following environment information:**
- OS:  Ubuntu 20.04
- Device: Wh-n150

**Additional context**
Used in petr_head sub_module

**Comment by punithsekar** [comment]
fyi @saichandax

**Comment by ayerofieiev-tt** [comment]
This looks like a combination of a slice view and eltwise. I don't think we will enable this specific syntax anywhere soon.

**Comment by punithsekar** [comment]
Will check for a workaround @ayerofieiev-tt .

**Comment by ctr-rsaravananTT** [comment]
Issue Resolved with a combination of Slice view and Eltwise

**Comment by sabira-mcw** [comment]
@ayerofieiev-tt 
We attempted to use a workaround involving slicing and assignment through intermediate variables (e.g., using slicing + concat ). While this generally works, it did not apply successfully in certain cases.

We attempted to assign values using dynamic slicing and indexing in the following scenario:
Ex:
query has shape: torch.Size([1, 6, 3587, 256])
reference_points_cam has shape: torch.Size([6, 1, 10000, 4, 2])
queries_rebatch is initialized with shape: [bs, num_cams, max_len, embed_dims] → [1, 6, 3587, 256]

reference_points_rebatch is initialized with shape: [bs, num_cams, max_len, D, 2] → [1, 6, 3587, 4, 2]

We're looping over the batch and cameras, and for each image, attempting to assign values using:

```
queries_rebatch[j, i, :len(index_query_per_img)] = query[j, index_query_per_img]
reference_points_rebatch[j, i, :len(index_query_per_img)] = reference_points_per_img[j, index_query_per_img]
```

- However, this kind of item assignment is not supported, likely due to the following reasons:
- The assignment relies on dynamic lengths per image (len(index_query_per_img)), which varies across samples.
- The indexing is non-contiguous, making it incompatible with static slicing .
- The assignment targets multi-dimensional slices with dynamically indexed selection from high-dimensional tensors, which the backend does not support in a direct item assignment.
Index lengths tested: [2974, 1268, 1302, 3587, 896, 939] — these vary per image

**Comment by dvartaniansTT** [comment]
@sabira-mcw , looks like the issue is still not resolved for you. please confirm.

**Comment by sabira-mcw** [comment]
Yes @dvartaniansTT , The issue still persists while indexing.

**Comment by keerthana-r-mcw** [comment]
@dvartaniansTT @sabira-mcw @ctr-rsaravananTT FYI - https://github.com/tenstorrent/tt-metal/issues/25517

**Comment by fahmedchanTT** [comment]
@aczajkowskiTT Adding you to assignees for now, since the linked cases are with you/your team

**Comment by fahmedchanTT** [comment]
@ntarafdar Are you looking at a similar issue elsewhere?

**Comment by fahmedchanTT** [comment]
Duplicated here: https://github.com/tenstorrent/tt-metal/issues/13723 as a slice_write issue

Will close this issue and track there
