### ISSUE TITLE
Incorrect ttnn.linear result for activations with shape Mx1xN

### ISSUE THREAD

**Issue by friedrich** [tenstorrent/tt-metal#16599]
When the activation tensor has shape Mx1xN and a bias of rank 2 is present, the result of ttnn.linear is incorrect.

We were able to work around the issue by making the bias a rank 3 tensor by adding another dimension of size 1. While this solution works flawlessly for our use-case, I believe that a bias of rank 3 should ideally not be required when calling `ttnn.linear`, as it makes the output always have at least rank 3.

**Test:**

```python
import pytest
import torch

import ttnn


@pytest.mark.parametrize("seed", range(10))
@pytest.mark.parametrize("inner_dim", [1, 2])
def test_linear_inner_dim_one(*, inner_dim: int, seed: int, device: ttnn.Device):
    torch.manual_seed(seed)

    k = 32
    m = 32

    x = torch.zeros([2, inner_dim, k])
    w = torch.zeros([k, m])
    b = torch.randn([1, m])

    tt_x = ttnn.from_torch(x, layout=ttnn.TILE_LAYOUT, device=device)
    tt_w = ttnn.from_torch(w, layout=ttnn.TILE_LAYOUT, device=device)
    tt_b = ttnn.from_torch(b, layout=ttnn.TILE_LAYOUT, device=device)

    tt_result = ttnn.linear(tt_x, tt_w, bias=tt_b)
    result = ttnn.to_torch(tt_result)

    assert torch.allclose(result[0], result[1])
```

The test runs `ttnn.linear` with a batch size of two and compares the outcome of the two batches. They should match, since the activations and weights are all zero. There seems to be access to uninitialized memory involved, so the problem may not always be visible. Therefore, the test is run multiple times. On our setup, the test succeeds with inner_dim=2 (as it should) and fails with inner_dim=1.

**Environment:**

* tt-metal version: main branch, commit https://github.com/tenstorrent/tt-metal/commit/5d9e93f6d4
* OS: Linux
* Distro: Ubuntu 20.04.6 LTS
* Kernel: 5.4.0-196-generic
* Platform: x86_64
* Python: 3.8.10
* FW Bundle Version: 80.10.0.0
* TT-Flash Version: 0.2.2.0
* CM FW Version: 2.27.0.0
* ETH FW Version: 6.9.0
* BM BL Version: 129.2.0.0
* BM App Version: 5.9.0.2

**Comment by zzigler-tt** [comment]
Hello, I'd like to prioritize this issue for remediation as the team is helping to bring up Stable Diffusion. 

@prajaramanTT Can you please ensure this item is assigned correctly, have remediation timeline, etc. 

FYI @mbahnasTT 

Thanks

**Comment by bbradelTT** [comment]
This specific combination makes linear use ttnn.add under the hood, and ttnn.add is the reason for this behaviour.

This boils down to
- adding a [2,1,32] tensor and a [1,1,32] tensor works and
- adding a [2,1,32] tensor and a [1,32] tensor doesn't work

@eyonland is this a known issue?

```
@pytest.mark.parametrize("inner_dim", [1, 2])
def test_add(device, inner_dim):
    m = 32
    x = torch.zeros([2, inner_dim, m])
    b = torch.zeros([1, 1, m])
    b2 = torch.zeros([1, m])
    tt_x = ttnn.from_torch(x, layout=ttnn.TILE_LAYOUT, device=device)
    tt_b = ttnn.from_torch(b, layout=ttnn.TILE_LAYOUT, device=device)
    tt_b2 = ttnn.from_torch(b2, layout=ttnn.TILE_LAYOUT, device=device)
    tt_result = ttnn.add(tt_x, tt_b)
    tt_result2 = ttnn.add(tt_x, tt_b2)
    result = ttnn.to_torch(tt_result)
    result2 = ttnn.to_torch(tt_result2)
    assert torch.allclose(result[0], result[1])
    print("2D Passed")
    assert torch.allclose(result2[0], result2[1])
    print("3D Passed")
```
Results in:
```
PASSED test_mean2.py::test_add[2]
FAILED test_mean2.py::test_add[1] - assert False
```

With the debug log:
```
test_mean2.py::test_add[1] ⠁ Initializing Chip                                                                                                                                                                      Detecting chips (found 2)                                                                                                                                                                                       
2025-01-16 21:30:16.085 | INFO     | SiliconDriver   - Opened PCI device 0; KMD version: 1.31.0, IOMMU: disabled
2025-01-16 21:30:16.097 | INFO     | SiliconDriver   - Detected PCI devices: [0]
2025-01-16 21:30:16.098 | INFO     | SiliconDriver   - Using local chip ids: {0} and remote chip ids {1}
2025-01-16 21:30:16.177 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.10.0 (Device 0)
2025-01-16 21:30:16.178 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.10.0 (Device 1)
                 Always | DEBUG    | Initializing firmware
                 Always | DEBUG    | Waiting for firmware init complete
                 Always | DEBUG    | Firmware init complete
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::add
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::repeat
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Launching Device Operation: "RepeatDeviceOperation"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	repeat_dim = 0
                     Op | DEBUG    | 	num_repeats = 2
                     Op | DEBUG    | 	output_mem_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([1, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::untilize
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Launching Device Operation: "Untilize"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	output_mem_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | 	use_multicore = true
                     Op | DEBUG    | 	use_pack_untilize = true
                     Op | DEBUG    | 	fp32_dest_acc_en = false
                     Op | DEBUG    | 	sub_core_grids = std::nullopt
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Using fast pack untilize.
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::untilize
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::slice
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::to_memory_config
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::to_memory_config
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::slice
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::tilize
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Launching Device Operation: "Tilize"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	output_mem_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | 	output_dtype = DataType::FLOAT32
                     Op | DEBUG    | 	use_multicore = false
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=RowMajorPageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::tilize
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::repeat
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::binary
                     Op | DEBUG    | Launching Device Operation: "BinaryDeviceOperation"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	binary_op_type = BinaryOpType::ADD
                     Op | DEBUG    | 	activations = std::nullopt
                     Op | DEBUG    | 	input_tensor_a_activation = std::nullopt
                     Op | DEBUG    | 	scalar = std::nullopt
                     Op | DEBUG    | 	memory_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | 	dtype = DataType::FLOAT32
                     Op | DEBUG    | 	worker_grid = {[(x=0,y=0) - (x=7,y=6)]}
                     Op | DEBUG    | 	compute_kernel_config = std::nullopt
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 	1: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::binary
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::add
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::add
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::binary
                     Op | DEBUG    | Launching Device Operation: "BinaryDeviceOperation"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	binary_op_type = BinaryOpType::ADD
                     Op | DEBUG    | 	activations = std::nullopt
                     Op | DEBUG    | 	input_tensor_a_activation = std::nullopt
                     Op | DEBUG    | 	scalar = std::nullopt
                     Op | DEBUG    | 	memory_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | 	dtype = DataType::FLOAT32
                     Op | DEBUG    | 	worker_grid = {[(x=0,y=0) - (x=7,y=6)]}
                     Op | DEBUG    | 	compute_kernel_config = std::nullopt
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 	1: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::binary
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::add
                     Op | DEBUG    | Launching External Operation: "(torch) __getitem__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) __getitem__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) allclose"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
2D Passed
                     Op | DEBUG    | Launching External Operation: "(torch) __getitem__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) __getitem__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) allclose"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) __repr__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) __repr__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
FAILED
test_mean2.py::test_add[2]                  Always | DEBUG    | Initializing firmware
                 Always | DEBUG    | Waiting for firmware init complete
                 Always | DEBUG    | Firmware init complete
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::to_layout
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::add
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::repeat
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Launching Device Operation: "RepeatDeviceOperation"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	repeat_dim = 0
                     Op | DEBUG    | 	num_repeats = 2
                     Op | DEBUG    | 	output_mem_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([1, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::untilize
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Launching Device Operation: "Untilize"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	output_mem_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | 	use_multicore = true
                     Op | DEBUG    | 	use_pack_untilize = true
                     Op | DEBUG    | 	fp32_dest_acc_en = false
                     Op | DEBUG    | 	sub_core_grids = std::nullopt
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Using fast pack untilize.
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::untilize
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::slice
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::to_memory_config
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::to_memory_config
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::slice
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::tilize
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Launching Device Operation: "Tilize"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	output_mem_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | 	output_dtype = DataType::FLOAT32
                     Op | DEBUG    | 	use_multicore = false
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=RowMajorPageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::old_infra_device_operation
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::tilize
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::repeat
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::binary
                     Op | DEBUG    | Launching Device Operation: "BinaryDeviceOperation"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	binary_op_type = BinaryOpType::ADD
                     Op | DEBUG    | 	activations = std::nullopt
                     Op | DEBUG    | 	input_tensor_a_activation = std::nullopt
                     Op | DEBUG    | 	scalar = std::nullopt
                     Op | DEBUG    | 	memory_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | 	dtype = DataType::FLOAT32
                     Op | DEBUG    | 	worker_grid = {[(x=0,y=0) - (x=7,y=6)]}
                     Op | DEBUG    | 	compute_kernel_config = std::nullopt
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 2, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 	1: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::binary
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::add
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::add
                     Op | DEBUG    | Started   C++ ttnn operation: ttnn::prim::binary
                     Op | DEBUG    | Launching Device Operation: "BinaryDeviceOperation"
                     Op | DEBUG    | Program Hash: 0
                     Op | DEBUG    | Program Cache Hit: false
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	binary_op_type = BinaryOpType::ADD
                     Op | DEBUG    | 	activations = std::nullopt
                     Op | DEBUG    | 	input_tensor_a_activation = std::nullopt
                     Op | DEBUG    | 	scalar = std::nullopt
                     Op | DEBUG    | 	memory_config = MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)
                     Op | DEBUG    | 	dtype = DataType::FLOAT32
                     Op | DEBUG    | 	worker_grid = {[(x=0,y=0) - (x=7,y=6)]}
                     Op | DEBUG    | 	compute_kernel_config = std::nullopt
                     Op | DEBUG    | Tensors Args:
                     Op | DEBUG    | 	0: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([2, 2, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 	1: Tensor(storage=DeviceStorage(memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)),tensor_spec=TensorSpec(logical_shape=Shape([1, 32]),tensor_layout=TensorLayout(dtype=DataType::FLOAT32,page_config=PageConfig(config=TilePageConfig(tile=Tile(tile_shape={32, 32},face_shape={16, 16},num_faces=4))),memory_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt),alignment=Alignment([32, 32]))))
                     Op | DEBUG    | 
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::prim::binary
                     Op | DEBUG    | Finished  C++ ttnn operation: ttnn::add
                     Op | DEBUG    | Launching External Operation: "(torch) __getitem__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) __getitem__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) allclose"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
2D Passed
                     Op | DEBUG    | Launching External Operation: "(torch) __getitem__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) __getitem__"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
                     Op | DEBUG    | Launching External Operation: "(torch) allclose"
                     Op | DEBUG    | Input std::vector<Tensor>:
                     Op | DEBUG    | 
3D Passed
PASSED

==================================================================================================== FAILURES ====================================================================================================
__________________________________________________________________________________________________ test_add[1] ___________________________________________________________________________________________________

device = <ttnn._ttnn.device.Device object at 0x7a9a13cbf270>, inner_dim = 1

    @pytest.mark.parametrize("inner_dim", [1, 2])
    def test_add(device, inner_dim):
        m = 32
        x = torch.zeros([2, inner_dim, m])
        b = torch.zeros([1, 1, m])
        b2 = torch.zeros([1, m])
        tt_x = ttnn.from_torch(x, layout=ttnn.TILE_LAYOUT, device=device)
        tt_b = ttnn.from_torch(b, layout=ttnn.TILE_LAYOUT, device=device)
        tt_b2 = ttnn.from_torch(b2, layout=ttnn.TILE_LAYOUT, device=device)
        tt_result = ttnn.add(tt_x, tt_b)
        tt_result2 = ttnn.add(tt_x, tt_b2)
        result = ttnn.to_torch(tt_result)
        result2 = ttnn.to_torch(tt_result2)
        assert torch.allclose(result[0], result[1])
        print("2D Passed")
>       assert torch.allclose(result2[0], result2[1])
E       assert False
E        +  where False = <built-in method allclose of type object at 0x7a9a526908c0>(TorchTensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n              0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), TorchTensor([[-0.9150, -0.2529, -1.5371, -0.0292,  0.1783, -0.2693, -0.8218,\n               2.7051,  0.1694, -1.0869,  1.7461, -0.1348,  0.3232,  1.3848,\n               0.8569, -0.7969, -0.0144,  0.1930,  1.0137, -0.8271,  0.5503,\n               2.3066,  0.2479,  0.7256,  0.2983, -1.1494,  0.2788, -1.0215,\n              -0.5630,  1.4307, -0.3496, -0.7061]]))
E        +    where <built-in method allclose of type object at 0x7a9a526908c0> = torch.allclose

test_mean2.py:1017: AssertionError
```

**Comment by eyonland** [comment]
This is a known issue.   I believe this test should pass on our new binary add operation called binary_ng that we expect to rollout next week.   Here's the example test we can add this case to  https://github.com/tenstorrent/tt-metal/blob/main/tests/ttnn/unit_tests/operations/eltwise/test_binary_bcast.py#L206

**Comment by bbradelTT** [comment]
@eyonland I tried with ttnn.experimental.add and the test passed. Please let me know once that is production ready and I will switch linear to use that.

**Comment by zzigler-tt** [comment]
@eyonland Please advise if you will be able to push out this item to production as it's a blocker for the development team who's bringing up Stable Diffusion. TY in advance for the support.

**Comment by eyonland** [comment]
ttnn.experimental.add is expected to become the new ttnn.add on Monday at COB.    Is it possible to unblock their development work over the next few days with ttnn.experimental.add until we can roll this fix out?

**Comment by bbradelTT** [comment]
Making the change would require to make two PRs including having to look at pipelines. I don't think that's worthwhile.

Hopefully they can wait until end of day Monday.

If they can make local changes, they can modify one line in ttnn/cpp/ttnn/operations/matmul/matmul.cpp
```
output_tensor = ttnn::add(output_tensor, bias.value(), std::nullopt, parameters.output_mem_config);
```
can be changed to
```
output_tensor = ttnn::experimental::add(output_tensor, bias.value(), std::nullopt, parameters.output_mem_config);
```
and update any includes if necessary.

**Comment by bbradelTT** [comment]
The new PR for binary ng requires opt in via an extra parameter. Once that is merged, the linear code will need to be updated.

Need to re-open this issue.

**Comment by nsorabaTT** [comment]
Primary issue raised here is resolved when using `use_legacy=false` in `matmul.cpp`. However, the resolution is blocked because the following call fails.

```c++
output_tensor = ttnn::add(
            /* lhs=*/output_tensor,
            /* rhs=*/bias.value(),
            /* output_dtype=*/std::nullopt,
            /* memory_config=*/parameters.output_mem_config,
            /* output=*/std::nullopt,
            /* post_activations=*/ttnn::SmallVector<unary::UnaryWithParam>(),
            /* lhs_activations=*/ttnn::SmallVector<unary::UnaryWithParam>(),
            /* rhs_activations=*/ttnn::SmallVector<unary::UnaryWithParam>(),
            /* use_legacy=*/false);
```

Where,
`lhs` is a tensor of shape [1, 1, 1, 39576]
`rhs` is a tensor of shape [1, 39576]
`memory_config` is WIDTH_SHARDED

Signature is:

```
RuntimeError: TT_FATAL @ /localdev/nsoraba/tt-metal/ttnn/cpp/ttnn/operations/eltwise/binary_ng/device/binary_ng_program_factory.cpp:169: current_shape[majorDim] == last_shard_shape[majorDim] and current_shape[minorDim] == last_shard_shape[minorDim]
E       info:
E       no un-even shard size support memory layout TensorMemoryLayout::WIDTH_SHARDED

```

@dchenTT

**Comment by nsorabaTT** [comment]
Python snippet to reproduce (though error signature is slightly different)

```python
import torch
import ttnn

def test_add_error(device):
    # Create input tensors with specified shapes
    input_shape = [1, 1, 1, 39576]
    bias_shape = [1, 39576]

    # Create random tensors
    torch_input = torch.randn(*input_shape, dtype=torch.bfloat16)
    torch_bias = torch.randn(*bias_shape, dtype=torch.bfloat16)

    # Convert to TTNN tensors with tile layout
    ttnn_input = ttnn.from_torch(torch_input, device=device, layout=ttnn.TILE_LAYOUT)
    ttnn_bias = ttnn.from_torch(torch_bias, device=device, layout=ttnn.TILE_LAYOUT)

    # Perform the add operation with the specified memory config
    ttnn_result = ttnn.add(
        ttnn_input,
        ttnn_bias,
        memory_config=ttnn.L1_WIDTH_SHARDED_MEMORY_CONFIG,
        use_legacy=False
    )
```

**Comment by dchenTT** [comment]
We currently do not support uneven sharding size when use_legacy=false. That explains it. We can easily support uneven shard size for HEIGHT sharding though. As when to support WIDTH and BLOCK, we shall discuss with @cmaryanTT

**Comment by nsorabaTT** [comment]
Thanks Debin for the quick triage.

Issue blocked by https://github.com/tenstorrent/tt-metal/issues/21172. To be taken up post resolution of that.

**Comment by nsorabaTT** [comment]
> Thanks Debin for the quick triage.
> 
> Issue blocked by [#21172](https://github.com/tenstorrent/tt-metal/issues/21172). To be taken up post resolution of that.

Additional bias cases in `tests/sweep_framework/sweeps/matmul/generality/linear.py` to be enabled after resolution of this issue.
Refer to https://github.com/tenstorrent/tt-metal/pull/21003 for more details.

**Comment by bbradelTT** [comment]
The original test in the description is still failing for me. Reopening.

@dchenTT what is the status of binary ng and turning it on for the add in linear?

**Comment by smehtaTT** [comment]
+ @cmaryanTT  to investigate

**Comment by cmaryanTT** [comment]
@dchenTT - can you please test this out with your latest fixes, with no use of use_legacy. Check both the original ttnn.linear call, and the simplified ttnn.add call later on. I think broadcast in general for this case should be working, but I'm not sure if this produces an uneven shard that we can't handle.

**Comment by bbradelTT** [comment]
Testing on a commit from this week: 813c49f51f

The pytest in the description passes. test_add_error from https://github.com/tenstorrent/tt-metal/issues/16599#issuecomment-2828991210 still fails:
```
E       MemoryError: std::bad_array_new_length
```

**Comment by dchenTT** [comment]
It is the first time for me to see using memory_config=ttnn.L1_WIDTH_SHARDED_MEMORY_CONFIG without specifying shard size and core grids and using ttnn.L1_MEMORY_CONFIG. I suppose it is automatic. I can reproduce and will continue to debug.

**Comment by dchenTT** [comment]
The test failure does not even reach stage of launching Device Operation: "BinaryNgDeviceOperation"

**Comment by dchenTT** [comment]
I am able to identify some mishandling in binary_ng code so the error message has moved forward. However, the actual problem for this issue is a feature binary_ng does not support. Currently binary_ng expects explicit shard spec if the (output) tensor is sharded. In this issue, since memory_config=ttnn.L1_WIDTH_SHARDED_MEMORY_CONFIG, the user expects binary_ng generate automatic shard spec. What priority it is to expect binary_ng to support the feature?

**Comment by bbradelTT** [comment]
> I am able to identify some mishandling in binary_ng code so the error message has moved forward. However, the actual problem for this issue is a feature binary_ng does not support. Currently binary_ng expects explicit shard spec if the (output) tensor is sharded. In this issue, since memory_config=ttnn.L1_WIDTH_SHARDED_MEMORY_CONFIG, the user expects binary_ng generate automatic shard spec. What priority it is to expect binary_ng to support the feature?

That sounds more involved. Since the example in the description works, please create a new issue for supporting the feature. Since there would be a workaround in splitting out the add, the priority would probably be not as high as this issue.

Please post a link to the new issue you create to this issue.

I'll close this one out.

**Comment by dchenTT** [comment]
@bbradelTT Issued created https://github.com/tenstorrent/tt-metal/issues/24316
