### ISSUE TITLE
External library conflicting with conftest.py

### ISSUE THREAD

**Issue by ssinghalTT** [tenstorrent/tt-metal#19681]
Hi,

We are using Yolo weights from ultralytics library (pip install ultralytics). But when I do that, there is a conflict in conftest.py.

Error message below:
```
pytest tests/ttnn/integration_tests/yolov9c/test_ttnn_yolov9c.py 
/home/ubuntu/test/main/tt-metal/python_env/lib/python3.8/site-packages/_pytest/config/__init__.py:329: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: ModuleNotFoundError: No module named 'tests.scripts' (from /home/ubuntu/test/main/tt-metal/conftest.py)
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ImportError while loading conftest '/home/ubuntu/test/main/tt-metal/conftest.py'.
conftest.py:22: in <module>
    from tests.scripts.common import run_process_and_get_result
E   ModuleNotFoundError: No module named 'tests.scripts'
```

But when I use a different version of ultralytics (ultralytics==8.2) we dont see the issue. Can we fix the conflict?

Steps to reproduce:

- Checkout branch [keerthana/ttnn_yolov9c_perf_tests](https://github.com/tenstorrent/tt-metal/tree/keerthana/ttnn_yolov9c_perf_tests)
- ./create_venv.sh (already has the ultralytics==8.2 library installation)
- source python_env/bin/activate
- pytest tests/ttnn/integration_tests/yolov9c/test_ttnn_yolov9c.py

You should not see the error above.

But if you uninstall and reinstall with the latest version, the test fails with above error.

- pip uninstall ultralytics
- pip install ultralytics
- pytest tests/ttnn/integration_tests/yolov9c/test_ttnn_yolov9c.py

**Comment by ssinghalTT** [comment]
@esmalTT any update on this?

cc: @mbahnasTT

**Comment by esmalTT** [comment]
I have opened a bug report here: https://github.com/ultralytics/ultralytics/issues/20078

Ideally, this `tests` package would never be installed on the users system.

**Comment by esmalTT** [comment]
I've opened a PR for `ultralytics` with a fix for this issue: https://github.com/ultralytics/ultralytics/pull/20079

**Comment by esmalTT** [comment]
My PR (https://github.com/ultralytics/ultralytics/pull/20079) has been merged. The issue should be resolved if we get the latest version of the library.

**Comment by esmalTT** [comment]
@ssinghalTT @mbahnasTT The next minor version (after 8.3.105) should have my fix. Please try it out when you have a chance.

**Comment by ssinghalTT** [comment]
@esmalTT  Still see the issue.

` pytest tests/ttnn/integration_tests/yolov9c/test_ttnn_yolov9c.py 
/home/ubuntu/test/gst/tt-metal/python_env/lib/python3.8/site-packages/_pytest/config/__init__.py:329: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: ModuleNotFoundError: No module named 'tests.scripts' (from /home/ubuntu/test/gst/tt-metal/conftest.py)
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ImportError while loading conftest '/home/ubuntu/test/gst/tt-metal/conftest.py'.
conftest.py:22: in <module>
    from tests.scripts.common import run_process_and_get_result
E   ModuleNotFoundError: No module named 'tests.scripts'
(python_env) ubuntu@test-ssinghal:~/test/gst/tt-metal$ pip list | grep ultralytics
ultralytics                             8.3.105
ultralytics-thop                        2.0.14
WARNING: You are using pip version 21.2.4; however, version 25.0.1 is available.
You should consider upgrading via the '/home/ubuntu/test/gst/tt-metal/python_env/bin/python3 -m pip install --upgrade pip' command.
`

**Comment by vigneshkeerthivasanx** [comment]
It might take effect from the next version of ultralytics as Evan mentioned **the next minor version (after 8.3.105) should have his fix**

**Comment by saichandax** [comment]
@vigneshkeerthivasanx , can we close this?
