### ISSUE TITLE
ttnn.conv2d DRAM slicing bad pcc

### ISSUE THREAD

**Issue by ipotkonjak-tt** [tenstorrent/tt-metal#21299]
### Describe the bug

Pcc fails for conv input of shape `[1, 128, 1024, 1024]`, `Cout = 3`, DRAM `slice_type = ttnn.Conv2dSliceWidth`, `num_slices = 16`.

### Steps to reproduce the issue

1. Go to `ipotkonjak/sdxl_vae_conv2d` (should be in main soon)
2. See `tests/ttnn/nightly/unit_tests/operations/conv/test_conv2d.py::test_conv2d_vae_sdxl`
3. Uncomment the failing test

### Expected behavior

<img width="2635" alt="Image" src="https://github.com/user-attachments/assets/005c4006-c1d7-42f3-9d8d-7d376dfdc4d0" />

**Comment by sankarmanoj-tt** [comment]
This should be fixed.

**Comment by ipotkonjak-tt** [comment]
Just ran the test case with the latest main. Unfortunately, pcc still appears to be 0.

**Comment by ipotkonjak-tt** [comment]
I've tried out your changes, VAE tests pass as well with this conv on device. We can close the issue when PR gets merged.

**Comment by sankarmanoj-tt** [comment]
The PR has been merged.
