### ISSUE TITLE
ttnn.concat fails with Out of Memory issue in L1

### ISSUE THREAD

**Issue by vigneshkeerthivasanx** [tenstorrent/tt-metal#21358]
### Describe the bug

`ttnn.concat` fails with Out of Memory issue in L1 and passed with DRAM. The issue cannot be reproduced in stand alone unit test for `ttnn.concat`, Hence, created using the model's sub-module test.

### Steps to reproduce the issue

1. checkout the branch: [vignesh/yolov10x_concat_issue](https://github.com/tenstorrent/tt-metal/tree/vignesh/yolov10x_concat_issue)
2. Run the following command:  `pytest tests/ttnn/integration_tests/yolov10/test_ttnn_yolov10.py::test_yolov10x_C2f`

### Expected behavior

The test is expected to PASS with the ttnn.concat in L1 memory config. But now it passes only for DRAM memory config.

### Please complete the following environment information

- OS version - Ubuntu 20.04
- Hardware - n150, n300

**Comment by saichandax** [comment]
Issue still persists.
Linking the issue as part of #27551

**Comment by cmaryanTT** [comment]
This should be resolved in the model, by reducing the space consumed by other tensors in L1. Concat is expected to be memory efficient, so its intermediate usage of L1 should be pretty well optimized (but not zero).

**Comment by Sudharsan-V** [comment]
The concat op is still failing with OOM issue when in L1 even in submodule level test mentioned above on main.
`E       RuntimeError: TT_THROW @ /home/ubuntu/sudharsan/tt-metal/tt_metal/impl/allocator/bank_manager.cpp:137: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 21299200 B L1 buffer across 64 banks, where each bank needs to store 333824 B, but bank size is only 1374208 B`

There are 5 inputs for this concat op each of shape [1, 1, 25600, 80] in L1

**Comment by amorrisonTT** [comment]
@fahmedchanTT @ntarafdar @vigneshkeerthivasanx the branch with the repro is no longer available

**Comment by fahmedchanTT** [comment]
@vigneshkeerthivasanx Can you please provide repro steps ?

**Comment by jungeunlim-TT** [comment]
@vigneshkeerthivasanx, @Sudharsan-V Could you check if this issue remains in the latest main branch ? It has been two months since the last comment.
