### ISSUE TITLE
Master Bug Collection - Qwen 2.5 failing on main after tt-transformers

### ISSUE THREAD

**Issue by stisiTT** [tenstorrent/tt-metal#22554]
The current pinned commit for Qwen 2.5 is before the transition to tt-transformers. Commits since then are not working as expected.

There are open tickets, from community as well as from the customer success work, that are blocking confirmation of Qwen's customer readiness.

That impacts Qwen 2.5: 72B, 7B, and 72BVL. 

There are OOM issues when [loading the checkpoint](https://github.com/tenstorrent/tt-metal/issues/22506), OOM issues with [Large Contexts](https://github.com/tenstorrent/tt-metal/issues/19890#issuecomment-2796592865), and [pytest errors](https://github.com/tenstorrent/tt-metal/issues/22419) (discovered when attempt to try a fix from the previous issue).

Organized below by model type and source (and so some of these links are repeats of the ones above.

Customer Success Issues - [72B](https://github.com/tenstorrent/tt-inference-server/issues/127), [72B](https://github.com/tenstorrent/tt-metal/issues/19890#issuecomment-2796592865), [7B](https://github.com/tenstorrent/tt-inference-server/issues/125), and [72B VL](https://github.com/tenstorrent/tt-inference-server/issues/233).

Community Bug - [here](https://github.com/tenstorrent/tt-metal/issues/22506)

## Summary of the above linked issues

1. [OOM when loading the checkpoint](https://github.com/tenstorrent/tt-metal/issues/22506): Successfully resolved by `v0.59.0-rc19` and closed.
2. [OOM issues with large contexts](https://github.com/tenstorrent/tt-metal/issues/19890#issuecomment-2796592865): Resolution suggested 6 weeks ago on April 11th, no response from reporter.
3. [Pytest error](https://github.com/tenstorrent/tt-metal/issues/22419): Looks like stale cache, resolution proposed.
4. [Customer team 72B](https://github.com/tenstorrent/tt-inference-server/issues/127): Reported blocked by #3, should be unblocked if above resolution correct.
5. [Customer team 7B](https://github.com/tenstorrent/tt-inference-server/issues/125): Bad output on vLLM. Will follow up with reporter, this is not seen when running the model's own simple_text_demo or accuracy tests.
6. [Customer team 72B-VL](https://github.com/tenstorrent/tt-inference-server/issues/233): Appears to be waiting for the code currently on branches to be merged to main and integrated with vLLM.

@stisiTT if this is a correct summary, consider tidying up the above / replacing it with this. Currently issues 2, 3 and 4 are waiting on the customer success team, issues 5 and 6 are waiting on the models team.

**Comment by milank94** [comment]
OOM issue was resolved here: https://github.com/tenstorrent/tt-metal/issues/22506

**Comment by yieldthought** [comment]
TODO: Update README.md to point to main with tt-transformers and not to models/demos/whatever

**Comment by stisiTT** [comment]
> OOM issue loading checkpoint was resolved here: [#22506](https://github.com/tenstorrent/tt-metal/issues/22506)

This did not resolve the issue. 

[qwen_fail.txt](https://github.com/user-attachments/files/20498021/qwen_fail.txt)

**Comment by stisiTT** [comment]
> TODO: Update README.md to point to main with tt-transformers and not to models/demos/whatever

@yieldthought 

I'm unsure what this means. Is there a suggestion that a different test is to be used for Qwen?

Updating to the latest RC was successful for a single "batch-1" run of Qwen, but subsequent repeats failed.

**Comment by stisiTT** [comment]
@yieldthought thanks for your help on #22419 . There's an outstanding question there but no critical anymore.

Still struggling to resolve #19890. 

Block size 64, max_num_blocks 1024: [qwen_long_context.txt](https://github.com/user-attachments/files/20561023/qwen_long_context.txt)

Block size 32, max_num_blocks 2048: PENDING

**Comment by yieldthought** [comment]
Running Qwen 2.5 models with >32k context is [considered a separate mode](https://huggingface.co/Qwen/Qwen2.5-72B-Instruct#processing-long-texts). We have not implemented the YARN extension from the default 32k sequence length to 128k described in HuggingFace and implement the models using the original config provided (32k context length).

Whilst there should not be out of memory errors, these are somewhat irrelevant right now because we would not expect good accuracy beyond 32k until this extension has been done, which is not currently scheduled.

**Comment by stisiTT** [comment]
Great, thanks for the feedback!
