### ISSUE TITLE
Race condition in FDMeshCommandQueue

### ISSUE THREAD

**Issue by dbabokin** [tenstorrent/tt-metal#22754]
### Describe the bug

From time to time I see crashes like this one below. It's not reproducible, but shows up from time to time. It might be something on our end, might be something in tt-metal. But these are our tests, which are not doing anything sophisticated, just serial execution of isolated ops. Any ideas how to debug this are welcome. If you have any switches to enable any "sanitizers" for this kind of race conditions probably?

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/tt_metal/impl/event/dispatch.cpp:192: event_completed == event_descriptor.event_id
info:
Event Order Issue: expected to read back completion signal for event 25 but got 1065369472!
backtrace:
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x2bad8b) [0x7316fc4bad8b]
 --- tt::tt_metal::event_dispatch::read_events_from_completion_queue(tt::tt_metal::ReadEventDescriptor&, int, unsigned short, unsigned char, tt::tt_metal::SystemMemoryManager&)
 --- tt::tt_metal::distributed::FDMeshCommandQueue::read_completion_queue_event(tt::tt_metal::distributed::MeshReadEventDescriptor&)
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x729c70) [0x7316fc929c70]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x729c3d) [0x7316fc929c3d]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x729bed) [0x7316fc929bed]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x729acd) [0x7316fc929acd]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x729a16) [0x7316fc929a16]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x72862b) [0x7316fc92862b]
 --- tt::tt_metal::distributed::FDMeshCommandQueue::read_completion_queue()
 --- void std::__invoke_impl<void, void (tt::tt_metal::distributed::FDMeshCommandQueue::*)(), tt::tt_metal::distributed::FDMeshCommandQueue*>(std::__invoke_memfun_deref, void (tt::tt_metal::distributed::FDMeshCommandQueue::*&&)(), tt::tt_metal::distributed::FDMeshCommandQueue*&&)
 --- std::__invoke_result<void (tt::tt_metal::distributed::FDMeshCommandQueue::*)(), tt::tt_metal::distributed::FDMeshCommandQueue*>::type std::__invoke<void (tt::tt_metal::distributed::FDMeshCommandQueue::*)(), tt::tt_metal::distributed::FDMeshCommandQueue*>(void (tt::tt_metal::distributed::FDMeshCommandQueue::*&&)(), tt::tt_metal::distributed::FDMeshCommandQueue*&&)
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x72f992) [0x7316fc92f992]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x72f955) [0x7316fc92f955]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_Debug/tt_metal/libtt_metal.so(+0x72f839) [0x7316fc92f839]
 --- /lib/x86_64-linux-gnu/libstdc++.so.6(+0xe62b3) [0x7316fd2792b3]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7316fcf17ac3]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7316fcfa9850]
```

### Steps to reproduce the issue

No easy way to reproduce this and that's the problem.

### Please complete the following environment information

- Ubuntu 22.04
- tt-metal stack of fairly recent version (several day behind main).

**Comment by ayerofieiev-tt** [comment]
From @afuller-TT 
Maybe related to 
https://github.com/tenstorrent/tt-metal/issues/21556#issuecomment-2855539752


@pgkeller can someone help take a look please?

**Comment by pgkeller** [comment]
Hi @dbabokin, do you have a test case you can share with us?  We have a lot of unit tests that don't hit this issue, w/o something to reproduce I'm not sure there is anything we can do to narrow it down further.  It's ok if the test doesn't repro deterministically, we can run it in a loop overnight or some such.  Thanks.

**Comment by dbabokin** [comment]
Message in https://github.com/tenstorrent/tt-metal/issues/21303 looks the same. We apparently hitting this issue with recent tt-metal. I'll try building the reproducer. But it seems to be reproducible only on one of our machines, but not on the others.

**Comment by dbabokin** [comment]
I stopped seeing this error on my machine, so I can't reproduce it anymore. Though nothing has changed, except probably the machine being rebooted. I put up a test that should reproduce this issue, though I can't prove it right now. I put the reporducer in this commit: https://github.com/dbabokin/tt-metal/commit/78fbbd33579f269c809c4989b7af5022995d7506 This should be handy for you to pick and build.

I'll wait till I see this error again and will rerun this repro to prove that it fails.

**Comment by dbabokin** [comment]
Today I'm able to reproduce this problem with the test I posted above. It failed for me in 14 seconds. Here's the log:
```
Iteration 719terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/tt_metal/impl/event/dispatch.cpp:192: event_completed == event_descriptor.event_id
info:
Event Order Issue: expected to read back completion signal for event 720 but got 3217844978!
backtrace:
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/ttnn/_ttnn.so(+0x19e447b) [0x76cf10be447b]
 --- tt::tt_metal::event_dispatch::read_events_from_completion_queue(tt::tt_metal::ReadEventDescriptor&, int, unsigned short, unsigned char, tt::tt_metal::SystemMemoryManager&)
 --- tt::tt_metal::distributed::FDMeshCommandQueue::read_completion_queue_event(tt::tt_metal::distributed::MeshReadEventDescriptor&)
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/tt_metal/libtt_metal.so(+0x72c2a0) [0x76cf0ed2c2a0]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/tt_metal/libtt_metal.so(+0x72c26d) [0x76cf0ed2c26d]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/tt_metal/libtt_metal.so(+0x72c21d) [0x76cf0ed2c21d]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/tt_metal/libtt_metal.so(+0x72c0fd) [0x76cf0ed2c0fd]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/tt_metal/libtt_metal.so(+0x72c046) [0x76cf0ed2c046]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/tt_metal/libtt_metal.so(+0x72ac5b) [0x76cf0ed2ac5b]
 --- tt::tt_metal::distributed::FDMeshCommandQueue::read_completion_queue()
 --- void std::__invoke_impl<void, void (tt::tt_metal::distributed::FDMeshCommandQueue::*)(), tt::tt_metal::distributed::FDMeshCommandQueue*>(std::__invoke_memfun_deref, void (tt::tt_metal::distributed::FDMeshCommandQueue::*&&)(), tt::tt_metal::distributed::FDMeshCommandQueue*&&)
 --- std::__invoke_result<void (tt::tt_metal::distributed::FDMeshCommandQueue::*)(), tt::tt_metal::distributed::FDMeshCommandQueue*>::type std::__invoke<void (tt::tt_metal::distributed::FDMeshCommandQueue::*)(), tt::tt_metal::distributed::FDMeshCommandQueue*>(void (tt::tt_metal::distributed::FDMeshCommandQueue::*&&)(), tt::tt_metal::distributed::FDMeshCommandQueue*&&)
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/tt_metal/libtt_metal.so(+0x731fc2) [0x76cf0ed31fc2]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/tt_metal/libtt_metal.so(+0x731f85) [0x76cf0ed31f85]
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build/tt_metal/libtt_metal.so(+0x731e69) [0x76cf0ed31e69]
 --- /lib/x86_64-linux-gnu/libstdc++.so.6(+0xe62b3) [0x76cf0d2c82b3]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x76cf0d04dac3]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x76cf0d0df850]

Aborted (core dumped)
```

**Comment by afuller-TT** [comment]
@dbabokin Could you build with `TSan` build config and reproduce?  Does TSan give a report?

If your run is at the C++ level, then it should Just Work (ie: instead of 'Debug' or 'Release' just put 'TSan' in however you trigger your build).

If you're doing this via Python, then you need to ALSO set `LD_PRELOAD=/usr/lib/llvm-17/lib/clang/17/lib/linux/libclang_rt.tsan-x86_64.so` when you launch the binary.

**Comment by dbabokin** [comment]
Does TSan build work for you? That's what I have:

```
> time ./build_metal.sh --build-type TSan
...
[318/1123] Generating FlatBuffers header /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_TSan/tt_metal/third_party/umd/device/tt_simulation_device_generated.h
FAILED: tt_metal/third_party/umd/device/tt_simulation_device_generated.h /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_TSan/tt_metal/third_party/umd/device/tt_simulation_device_generated.h
cd /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_TSan/tt_metal/third_party/umd/device && /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_TSan/_deps/flatbuffers-build/flatc --cpp -o /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_TSan/tt_metal/third_party/umd/device /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/tt_metal/third_party/umd/device/simulation/tt_simulation_device.fbs
FATAL: ThreadSanitizer: unexpected memory mapping 0x59da52a32000-0x59da52a6a000
[319/1123] Building CXX object CMakeFiles/metal_common_pch.dir/cmake_pch.hxx.pch
ninja: build stopped: subcommand failed.

real    1m36.718s
user    1m4.573s
sys     0m24.699s
```

**Comment by afuller-TT** [comment]
Uff.  Never seen that.  And I cannot reproduce (tried ac1aeeef72fabe6de00f6aa1663f7f7efd14bc91 with `./build_metal.sh --build-type TSan` and it succeeded).  Could try turning off the simulator (`TT_UMD_BUILD_SIMULATION`) if you're not needing that; but I suspect that's more a symptom than the problem.  AFAIK Clang installs all the bits needed for TSan by default, so we shouldn't have a half-state there.

I did find this: https://github.com/google/sanitizers/issues/1716 do you have a new kernel by chance?  I'm on v5.15 and the bug report says 6.6.6 is bad.

**Comment by dbabokin** [comment]
I have Ubuntu 22.04 with `6.8.0-59-generic` kernel...

**Comment by afuller-TT** [comment]
Does using setarch as mentioned in this comment: https://github.com/google/sanitizers/issues/1716#issuecomment-1902785075 allow TSan to run on your system?

Oh wait, it's part of the built.

Not sure if that flows child procs?  Does running the build with setarch allow it to build (and then need to use setarch again to run the final binary)?

**Comment by dbabokin** [comment]
I'm running in the Docker container and it doesn't have rights to change ASLR. I disabled ASLR on the host and rerun the build, now it works.

Running the test now. It runs noticeably slower and doesn't fail so far. I'll keep running it.

**Comment by dbabokin** [comment]
I reproduced the failure with TSan, the error message the same, so TSan didn't detect any issues:
```
Iteration 667988terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/tt_metal/impl/event/dispatch.cpp:192: event_completed == event_descriptor.event_id
info:
Event Order Issue: expected to read back completion signal for event 667989 but got 602454!
backtrace:
 --- void tt::assert::tt_throw_impl<fmt::v11::fstring<unsigned int const&, unsigned int const&>, unsigned int, unsigned int>(char const*, int, char const*, char const*, fmt::v11::fstring<unsigned int const&, unsigned int const&> const&, unsigned int const&, unsigned int const&)
 --- void tt::assert::tt_throw<unsigned int, unsigned int>(char const*, int, char const*, char const*, fmt::v11::fstring<unsigned int const&, unsigned int const&>::t, unsigned int const&, unsigned int const&)
 --- tt::tt_metal::event_dispatch::read_events_from_completion_queue(tt::tt_metal::ReadEventDescriptor&, int, unsigned short, unsigned char, tt::tt_metal::SystemMemoryManager&)
 --- tt::tt_metal::distributed::FDMeshCommandQueue::read_completion_queue_event(tt::tt_metal::distributed::MeshReadEventDescriptor&)
 --- tt::tt_metal::distributed::FDMeshCommandQueue::read_completion_queue()
 --- /workspaces/oxpython/components/backends/tenstorrent/externals/tt-metal/build_TSan/tt_metal/libtt_metal.so(+0x4b629c) [0x7ffff56b629c]
 --- /lib/x86_64-linux-gnu/libstdc++.so.6(+0xe62b3) [0x7ffff44c82b3]
 --- ./tt-train/sources/examples/crash_repro_22754/crash_repro_22754(+0x63eaf) [0x5555555b7eaf]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7ffff424dac3]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7ffff42df850]
```

**Comment by dbabokin** [comment]
Look like the error happens when there multiple users trying to run something one the system. I haven't proved that, but I'm trying to run the experiments that can prove or disprove that.

**Comment by jbaumanTT** [comment]
I haven't been able to repro with your change locally. When you get a chance, could you try with https://github.com/tenstorrent/tt-metal/tree/refs/heads/jbauman/barrierread ? It adds some extra barriers when writing to the completion queue, which would prevent one possible cause for this issue.

**Comment by dbabokin** [comment]
I have a strong feeling that this happens when two users run simultaneously on the same machine. Can you try running two workloads on the same machine from two different processes?

**Comment by jbaumanTT** [comment]
I still haven't been able to repro when running two instances of the test at once. Just double-checking, but when you say "running two workloads on the same machine from two different processes" you mean against two separate devices, correct?

**Comment by dbabokin** [comment]
No, it's agains the same device. We, by default, use "device 0". We have a number of developers machines and have number of developers who use these machines. We don't control who is using what. And we see these problems on the machines that are used by the most of the developers.

My expectation was that if the device is busy, the driver will basically either reject to run the job, or will stall until it's released. Talking today to @ayerofieiev-tt I realized that UMD does nothing of that. So probably the right way to handle this bug is simply to request UMD to not allow the second job to run (at all or until the device is able to handle it).

**Comment by broskoTT** [comment]
This was fixed by https://github.com/tenstorrent/tt-umd/issues/971, which @dbabokin confirmed.
Will be merged in metal by: https://github.com/tenstorrent/tt-metal/pull/23442

**Comment by broskoTT** [comment]
Blocked by https://github.com/tenstorrent/tt-metal/issues/23749

**Comment by anatarajan-tt** [comment]
I'm having this same issue as well when running virtualized multi-host(using docker)training

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ /mnt/anatarajan/tt-metal/tt_metal/impl/event/dispatch.cpp:192: event_completed == event_descriptor.event_id
info:
Event Order Issue: expected to read back completion signal for event 109 but got 0!
backtrace:
 --- /mnt/anatarajan/tt-metal/build/lib/libtt_metal.so(+0x1ee809) [0x7f1461255809]
 --- /mnt/anatarajan/tt-metal/build/lib/libtt_metal.so(+0x385dba) [0x7f14613ecdba]
 --- tt::tt_metal::distributed::FDMeshCommandQueue::read_completion_queue_event(tt::tt_metal::distributed::MeshReadEventDescriptor&)
 --- tt::tt_metal::distributed::FDMeshCommandQueue::read_completion_queue()
 --- /lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc253) [0x7f145eab3253]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f145e73bac3]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7f145e7cd850]
```

Unlike mentioned above, I get it every time so my hypothesis is that since the communication time is really low(all on the same physical host) the race condition is more prevalent

Edit: Also, I'm the only one running a workload so it's not necessarily because of multiple jobs on a device

**Comment by anatarajan-tt** [comment]
It seems it was actually the same issue caused due to the n300 device mapping. Solved by changing the mapping

**Comment by pgkeller** [comment]
@dbabokin can this be closed?

**Comment by dbabokin** [comment]
> [@dbabokin](https://github.com/dbabokin) can this be closed?

If I'm not missing something, not before https://github.com/tenstorrent/tt-metal/issues/23749 is resolved.

**Comment by broskoTT** [comment]
So #23749 is now resolved, but there are a couple more issues, failures can be seen in https://github.com/tenstorrent/tt-metal/actions/runs/16385969324

Closing the cluster hangs in t3k tests, https://github.com/tenstorrent/tt-metal/actions/runs/16385969324/job/46365814242, tracking issue: https://github.com/tenstorrent/tt-umd/issues/1108

Profiler regressions tests show that cluster is trying to be opened multiple times without being closed properly, https://github.com/tenstorrent/tt-metal/actions/runs/16385969324/job/46365814986, tracking issue: https://github.com/tenstorrent/tt-metal/issues/25388

For other issues in the run, I can revisit them after these two are fixed, since I suspect they might be correlated.

**Comment by tt-rkim** [comment]
We're still seeing something similar: https://github.com/tenstorrent/tt-metal/actions/runs/16425007958/job/46413940736

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ /work/tt_metal/impl/event/dispatch.cpp:191: event_completed == event_descriptor.event_id
info:
Event Order Issue: expected to read back completion signal for event 1 but got 0!
backtrace:
```

**Comment by broskoTT** [comment]
Here's a new run with fails which aren't seen on main branch: https://github.com/tenstorrent/tt-metal/actions/runs/16532905829

So here's the new state, and what is failing:
- t3k tests not failing anymore, probably fixed by https://github.com/tenstorrent/tt-metal/issues/25377 or by https://github.com/tenstorrent/tt-metal/issues/25758
- profiler regression tests still failing, tracked by: https://github.com/tenstorrent/tt-metal/issues/25388
- model wormhole_b0 tests failing, seems like a host hang, could be a hang over a lock but I'm not sure why since the destructors seem like they properly executed. Tracked by https://github.com/tenstorrent/tt-umd/issues/1132
- ttnn group test 1 fails, could be related to one of the above, but not sure: https://github.com/tenstorrent/tt-umd/issues/1133

**Comment by fahmedchanTT** [comment]
@broskoTT Do we have an update on this issue ?

**Comment by tt-rkim** [comment]
Is this related? https://github.com/tenstorrent/tt-metal/actions/runs/17066200724/job/48384333779

```
2025-08-19 10:19:36.233 | INFO     | ttnn.device:__init__:138 - Using default dispatch core type for this system: DispatchCoreType.ETH
2025-08-19 10:19:36.233 | INFO     | ttnn.device:__init__:140 - Using default dispatch core axis for this system: DispatchCoreAxis.ROW
2025-08-19 10:19:38.476 | WARNING  | ttnn.model_preprocessing:from_torch:533 - ttnn: model cache can be enabled by passing model_name argument to preprocess_model[_parameters] and setting env variable TTNN_CONFIG_OVERRIDES='{"enable_model_cache": true}'
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ /project/tt_metal/impl/event/dispatch.cpp:191: event_completed == event_descriptor.event_id
info:
Event Order Issue: expected to read back completion signal for event 2 but got 1018084554!
backtrace:
```

**Comment by broskoTT** [comment]
The issue tt-rkim posted doesn't seem related.

I'm actively debugging one of the failures. However it is on @mo-tenstorrent to provide update for https://github.com/tenstorrent/tt-metal/issues/25388

**Comment by broskoTT** [comment]
For model wormhole_b0 tests failing, found and fixed the issue: https://github.com/tenstorrent/tt-metal/pull/27158
For ttnn failures, created a metal issue: https://github.com/tenstorrent/tt-metal/issues/27163

So the current state is that these two issues are blocking:
- profiler regression tests failing, tracked by: https://github.com/tenstorrent/tt-metal/issues/25388
- ttnn jupyter tests failing, tracked by: https://github.com/tenstorrent/tt-metal/issues/27163

**Comment by fahmedchanTT** [comment]
@broskoTT I'm unclear on the state of this issue, can you please provide an update?

**Comment by broskoTT** [comment]
I provided the latest update from UMD's side in the last comment, leftover work items are on tt-metal's plate.
I believe @mo-tenstorrent is working on resolving the linked issues?

**Comment by broskoTT** [comment]
Seems like all the issues were fixed.
I'm now testing this with new runs, and if they succeed will make the change in UMD and push to metal

**Comment by broskoTT** [comment]
There's actually still one failure discussed now on https://github.com/tenstorrent/tt-metal/issues/27163

**Comment by broskoTT** [comment]
Seems like there is another issue which needs to get resolved: https://github.com/tenstorrent/tt-metal/issues/28216
This issue led to a revert of fixes to the other two mentioned metal issues a few comments above

**Comment by mo-tenstorrent** [comment]
`get_arch_name` was not the trigger on [this](#28216 ) and the cache misses there are due to another bug. 

The real reason https://github.com/tenstorrent/tt-metal/pull/27805 causes regression was because many models end up calling `get_arch_name` on every op. The call to `PCIDevice::enumerate_devices_info()` which is part of the new method, is long (~80us) and with 1000 of ops' calls the overhead is adding up. 

Need to cache arch name so only the first call to get_arch_name incurs the long call.

**Comment by broskoTT** [comment]
So previously it was faster, even though it did full driver initialization and device startup, only because this call is cached and is called many times? Interesting. At least the fix is easy, please let us know when you fix it

**Comment by mo-tenstorrent** [comment]
metal context is a singleton alive for the life time of the process. Only the first call, if metal context was not up, too a long time. Yeah fix is coming

**Comment by fahmedchanTT** [comment]
@mo-tenstorrent Any updates this here?

**Comment by mo-tenstorrent** [comment]
The regression issue mentioned above is fixed.However, [#27163](https://github.com/tenstorrent/tt-metal/issues/27163) issue was not reproducible locally. I am still not sure how CI can behave differently.

**Comment by broskoTT** [comment]
In the latest testrun, I still see failures on the same test:

tests/ttnn/unit_tests/test_tutorials.py::test_ttnn_notebook_tutorials[notebook_path=ttnn/tutorials/2025_dx_rework/ttnn_mlp_inference_mnist.ipynb] FAILED

https://github.com/tenstorrent/tt-metal/actions/runs/17919080412/job/50949583170

@mo-tenstorrent will you be able to debug this?

**Comment by mo-tenstorrent** [comment]
Yes looking at it now.

As per @broskoTT suggestion, I can repro locally using:
```
TT_METAL_ENABLE_ERISC_IRAM=1 pytest tests/ttnn/unit_tests -xv --splits 12 --group 1 -m "not disable_fast_runtime_mode"
```

**Comment by mo-tenstorrent** [comment]
TTNN notebook tests spin their own subprocesses which reopen the umd device driver. When called as part of a collection of other pytests tests, because ttnn.so doesn't die, tt_cluster destructor is not called and so umd device is not closed. 

I moved these tests in to their own folder and run them separately so the notebook sub processes spin up and down their own ttnn.so and hence open and close device properly. This is how calling the suite looks like, where you can see each notebook is doing its own open and close 

<img width="1601" height="907" alt="Image" src="https://github.com/user-attachments/assets/2e5d67ed-329a-4b66-94d2-d96a48e2d2a4" />

APC with after the move: https://github.com/tenstorrent/tt-metal/actions/runs/17956230693

**Comment by fahmedchanTT** [comment]
Closing as this looks resolved.
