### ISSUE TITLE
Qwen2.5 7B Instruct Failing

### ISSUE THREAD

**Issue by stisiTT** [tenstorrent/tt-metal#24098]
### Describe the bug

Qwen2.5 fails for higher context lengths than 512. Overall, failing [Model Readiness](https://github.com/orgs/tenstorrent/projects/130/views/2?filterQuery=7B&pane=issue&itemId=116278756&issue=tenstorrent%7Ctt-inference-server%7C332) from Customer Success POV.

Error below, full logs pasted:

```
ERROR 06-23 17:23:30 [engine.py:163] RuntimeError: TT_THROW @ /home/container_app_user/tt-metal/tt_metal/impl/program/program.cpp:896: tt::exception
ERROR 06-23 17:23:30 [engine.py:163] info:
ERROR 06-23 17:23:30 [engine.py:163] Statically allocated circular buffers on core range [(x=0,y=0) - (x=7,y=7)] grow to 1724640 B which is beyond max L1 size of 1499136 B
```

### Steps to reproduce the issue

Using vLLM server and [tt-inference-server](https://github.com/tenstorrent/tt-inference-server/tree/dev):

Using "benchmarks" workflow, that is:
`python run.py --model "Qwen2.5-7B-Instruct" --workflow benchmarks --device n300 --docker-server`

[run_2025-06-24_12-59-14_id_tt-transformers_Qwen2.5-7B-Instruct_n300_benchmarks.log](https://github.com/user-attachments/files/20889325/run_2025-06-24_12-59-14_id_tt-transformers_Qwen2.5-7B-Instruct_n300_benchmarks.log)
[vllm_2025-06-24_12-57-18_Qwen2.5-7B-Instruct_n300_server.log](https://github.com/user-attachments/files/20889324/vllm_2025-06-24_12-57-18_Qwen2.5-7B-Instruct_n300_server.log)

Note: must update model_configs.py from tt-inference-server to use updated tt-metal and vllm commits. One can comment out all other Model Configs and edit Qwen2.5-7B-Instruct to have the following update:
```
ModelConfigTemplate(
        impl=tt_transformers_impl,
        device_model_spec_map={
            DeviceTypes.N300: DeviceModelSpec(
                max_concurrency=32,
                max_context=128 * 1024,
                default_impl=True,
            ),
            DeviceTypes.T3K: DeviceModelSpec(
                max_concurrency=32,
                max_context=128 * 1024,
                default_impl=True,
            ),
        },
        weights=["Qwen/Qwen2.5-7B", "Qwen/Qwen2.5-7B-Instruct"],
        tt_metal_commit="v0.59.0",
        vllm_commit="f028da1",
        status="testing",
```

### Expected behavior

Successful return of decoded output sequence

### Please complete the following environment information

internal n300 lab machine
tt_metal_commit="v0.59.0",
vllm_commit="f028da1",

**Comment by sraizada-tt** [comment]
should be fixed now, please checkout latest main

**Comment by milank94** [comment]
@stisiTT does this need a retest?

**Comment by stisiTT** [comment]
@sraizada-tt Still facing hangs:

```tt_metal_commit="v0.61.0-rc1",
vllm_commit="3dc6c31",
```
hangs after 8k at 16k trace capture (batch-1)

```
2025-07-22 01:38:46.847 | INFO     | models.tt_transformers.tt.generator:prefill_forward_text:79 - Prefilling User 1
2025-07-22 01:38:50.202 | INFO     | models.tt_transformers.tt.generator:prefill_forward_text:120 - Finished prefill for all users up to 8191 tokens, Starting decode...
INFO 07-22 01:38:50 [metrics.py:540] Avg prompt throughput: 1008.6 tokens/s, Avg generation throughput: 7.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.2%, CPU KV cache usage: 0.0%.
INFO 07-22 01:38:55 [metrics.py:540] Avg prompt throughput: 1632.1 tokens/s, Avg generation throughput: 18.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.2%, CPU KV cache usage: 0.0%.
INFO 07-22 01:38:58 logger.py:39] Received request cmpl-bffc024a96ed4bec9fa053a37b1344a5-0: prompt: ' theme先前_as�"The PhraseDeep CONSTvertisingSUPER.CO.ItemStackFacu', params: SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.05, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, ignore_eos=True, max_tokens=64, min_tokens=64, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, guided_decoding=None, extra_args=None), prompt_token_ids: [6912, 109977, 11898, 5691, 2073, 785, 68000, 33464, 29602, 29924, 90886, 86301, 94803, 94667, 25493, 22135, 144685, 132122, 124398, 125591, 33626, 114415, 143164, 102364, 36408, 43749, 5127, 79, 24224, 562, 19997, 114760, 39567, 46638, 18193, 98638, 148368, 100378, 133184, 78422, 122445, 12253, 147121, 21922, 66898, 92109, 48807, 40409, 32854, 59861, 81209, 121042, 140297, 33441, 62696, 96035, 3081, 30285, 46454, 131971, 124375, 64202, 115320, 93298], lora_request: None, prompt_adapter_request: None.
INFO:     172.17.0.1:47424 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 07-22 01:38:58 [engine.py:313] Added request cmpl-bffc024a96ed4bec9fa053a37b1344a5-0.
2025-07-22 01:38:58.486 | INFO     | models.tt_transformers.tt.generator:prefill_forward_text:79 - Prefilling User 1
```

**Comment by stisiTT** [comment]
Resolved failing issues. There may be further tickets for this model but this bug is considered resolved.

Thank you!
