### ISSUE TITLE
Fabric Connection Stress Test Fails on Blackhole LLMBox

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#25288]
test `./build/test/tt_metal/tt_fabric/fabric_unit_tests --gtest_filter="Fabric1DMuxFixture.TestFabricMuxStressOpenClose"` either causes a segmentation fault or crashes the system (bh-31) when run from main

**Comment by abhullar-tt** [comment]
there were some noc_inline_dw_writes that should have been targeting L1 but were marked as targeting stream registers. branch `abhullar/inline-bh` has some fixes but the stress test now hits a watcher assert in the edm kernel due to invalid packet:

repro cmd:
```
git checkout abhullar/inline-bh
TT_METAL_WATCHER_DISABLE_NOC_SANITIZE=1 TT_METAL_WATCHER=5 TT_METAL_WATCHER_NOINLINE=1 ./build/test/tt_metal/tt_fabric/fabric_unit_tests --gtest_filter=Fabric1DMuxFixture.TestFabricMuxStressOpenClose
```

**Comment by pgkeller** [comment]
@SeanNijjar just confirming, this is fixed right and can be closed?

**Comment by SeanNijjar** [comment]
oh yes it should have been closed. I think from the BH project perspective though we can definitely close. I'll keep it open on fabric board though while I validated it's properly enabled/passing in pipelines.

**Comment by SeanNijjar** [comment]
This is still hanging but I think fabric team should still own this given the original issues have been fixed broadly speaking.

**Comment by SeanNijjar** [comment]
FYI @ubcheema

**Comment by aagarwalTT** [comment]
Update: I was able to successfully run - 
`for i in {0..10}; do TT_METAL_USE_MGD_2_0=1 ./build/test/tt_metal/tt_fabric/fabric_unit_tests --gtest_filter="Fabric1DMuxFixture.*"; done`
 on `bh-db-03` which appears to be a 1X2 system. Will try enabling in CI

**Comment by SeanNijjar** [comment]
Amazing! @aagarwalTT

**Comment by aagarwalTT** [comment]
Passing run: https://github.com/tenstorrent/tt-metal/actions/runs/17844929623
PR: https://github.com/tenstorrent/tt-metal/pull/28887
