### ISSUE TITLE
Loss of PCC in Welfords algorithm using short init for transpose in wormhole.

### ISSUE THREAD

**Issue by amahmudTT** [tenstorrent/tt-metal#27334]
### Describe the bug

Using short version of init for transpose on wormhole causes loss of PCC in Welfords algorithm. 

### Steps to reproduce the issue

1. Go to branch amahmud/lnorm_good   (ad79d5a2ef5bec58e33b7d4fe794fe4cc19bc97c) (never mind the word good)
2. Run 

```pytest ./tests/ttnn/unit_tests/operations/fused/test_layer_norm.py::test_large_layer_norm_with_weight_bias_and_residual_input```

The PCC is worse compared to full init, more over it is non deterministic. If you go to file 

```
ttnn/cpp/ttnn/operations/normalization/layernorm/device/kernels/compute/layernorm_large_tensor_welford.cpp
```
at around line 125, you will see the call to transpose_wh_init/transpose_wh_init_short, here using the longer init produces better results.

### Expected behavior

PCC values should be good and deterministic with the shorter version of transpose init.

**Comment by amahmudTT** [comment]
@bbradelTT @vsureshTT  Tracking the PCC issue related to transpose here.

**Comment by amahmudTT** [comment]
Found the reason for determinsitic part of  pcc loss.  The config registers are quite different for math and unpacker before the computation for transpose starts. 

```
  │ Format_SrcA       │ TensixDataFormat.Tf32    │                                                                                                          |  │ Format_SrcA       │ TensixDataFormat.Float16_b │
  │ Format_SrcB       │ TensixDataFormat.Tf32    │                                                                                                          |  │ Format_SrcB       │ TensixDataFormat.Float16_b │
  │ Format_Dstacc     │ TensixDataFormat.Float32 │                                                                                                          |  │ Format_Dstacc     │ TensixDataFormat.Float32   │
  │ Fp32_enabled      │ True                     │                                                                                                          |  │ Fp32_enabled      │ True                       │
  │ SFPU_Fp32_enabled │ True                     │                                                                                                          |  │ SFPU_Fp32_enabled │ True                       │
  │ INT8_math_enabled │ False                    │                                                                                                          |  │ INT8_math_enabled │ False                      │
  └───────────────────┴──────────────────────────┘                                                                                                          |  └───────────────────┴────────────────────────────┘
  UNPACKER                                                                                                                                                  |  UNPACKER
  ┌─────────────────────────┬───────────────────────┬───────────────────────┐   ┌────────────────────┬──────────────────────────┬──────────────────────────┐|  ┌─────────────────────────┬───────────────────────┬────────────────────────────┐   ┌────────────────────┬──────────────────────────┬────────────────────────────┐
  │ UNPACK CONFIG           │ REG_ID = 1            │ REG_ID = 2            │   │ TILE DESCRIPTOR    │ REG_ID = 1               │ REG_ID = 2               │|  │ UNPACK CONFIG           │ REG_ID = 1            │ REG_ID = 2                 │   │ TILE DESCRIPTOR    │ REG_ID = 1               │ REG_ID = 2                 │
  ├─────────────────────────┼───────────────────────┼───────────────────────┤   ├────────────────────┼──────────────────────────┼──────────────────────────┤|  ├─────────────────────────┼───────────────────────┼────────────────────────────┤   ├────────────────────┼──────────────────────────┼────────────────────────────┤
  │ out_data_format         │ TensixDataFormat.Tf32 │ TensixDataFormat.Tf32 │   │ in_data_format     │ TensixDataFormat.Float32 │ TensixDataFormat.Float32 │|  │ out_data_format         │ TensixDataFormat.Tf32 │ TensixDataFormat.Float16_b │   │ in_data_format     │ TensixDataFormat.Float32 │ TensixDataFormat.Float16_b │

```

**Comment by amahmudTT** [comment]
Okay the deterministic case is found. The math source format is not updated during reconfiguring or initializing in short form and remains at blfoat16_b. Thus even though there is TF32 data in source registers, math will read only 16 bits of those.

**Comment by amahmudTT** [comment]
Okay here is the thing, when I fix the issue, both short and init have the same PCC, but the PCC is something between full init and half init, even if I call the full init after reconfiguring the data format. Which means the change in the reconfiguration function is having effect in other places too. So I checked which formats are being reconfigured, I saw at a later stage we reconfigure to float_16, so for experimentation I reconfigured only when it was TF32. then the PCC value went back high again. Which means at some point you are mistakenly recconfiguring to a lower precision data type and losing some precision, but my code change is correct. @bbradelTT @vsureshTT.

**Comment by amahmudTT** [comment]
@vsureshTT If you cherry pick the commit in the PR https://github.com/tenstorrent/tt-llk/pull/607, it may remove all the PCC discrepancies between short and full inits. Could you confirm ?

I will try to focus on the non-deterministic behavior on PCC now.

**Comment by amahmudTT** [comment]
For the non-deterministic PCC issue I think its not worth chasing this kernel since its too big. A very similar issue is encountered in this bug https://github.com/tenstorrent/tt-metal/issues/27278. Where transpose and permute has bad pcc in slow dispatch mode with bfloat16, if they are the same error I have much better chances in catching it with the mentioned issue. But better keep this open, lest they are not the same.

**Comment by bbradelTT** [comment]
Thanks for looking into this @amahmudTT 

@amahmudTT @nvelickovicTT this issue and issues like it have me worried about the init interface. It seems impossible for op kernel writers to find the right set of function calls + parameters to have correct output. We need a lot of support from the LLK team. That is slowing down both ops and llk teams. I hope this gets cleaned up with the API revamp and Quasar updates.

**Comment by bbradelTT** [comment]
> Found the reason for determinsitic part of pcc loss. The config registers are quite different for math and unpacker before the computation for transpose starts.
> 
> ```
>   │ Format_SrcA       │ TensixDataFormat.Tf32    │                                                                                                          |  │ Format_SrcA       │ TensixDataFormat.Float16_b │
>   │ Format_SrcB       │ TensixDataFormat.Tf32    │                                                                                                          |  │ Format_SrcB       │ TensixDataFormat.Float16_b │
>   │ Format_Dstacc     │ TensixDataFormat.Float32 │                                                                                                          |  │ Format_Dstacc     │ TensixDataFormat.Float32   │
>   │ Fp32_enabled      │ True                     │                                                                                                          |  │ Fp32_enabled      │ True                       │
>   │ SFPU_Fp32_enabled │ True                     │                                                                                                          |  │ SFPU_Fp32_enabled │ True                       │
>   │ INT8_math_enabled │ False                    │                                                                                                          |  │ INT8_math_enabled │ False                      │
>   └───────────────────┴──────────────────────────┘                                                                                                          |  └───────────────────┴────────────────────────────┘
>   UNPACKER                                                                                                                                                  |  UNPACKER
>   ┌─────────────────────────┬───────────────────────┬───────────────────────┐   ┌────────────────────┬──────────────────────────┬──────────────────────────┐|  ┌─────────────────────────┬───────────────────────┬────────────────────────────┐   ┌────────────────────┬──────────────────────────┬────────────────────────────┐
>   │ UNPACK CONFIG           │ REG_ID = 1            │ REG_ID = 2            │   │ TILE DESCRIPTOR    │ REG_ID = 1               │ REG_ID = 2               │|  │ UNPACK CONFIG           │ REG_ID = 1            │ REG_ID = 2                 │   │ TILE DESCRIPTOR    │ REG_ID = 1               │ REG_ID = 2                 │
>   ├─────────────────────────┼───────────────────────┼───────────────────────┤   ├────────────────────┼──────────────────────────┼──────────────────────────┤|  ├─────────────────────────┼───────────────────────┼────────────────────────────┤   ├────────────────────┼──────────────────────────┼────────────────────────────┤
>   │ out_data_format         │ TensixDataFormat.Tf32 │ TensixDataFormat.Tf32 │   │ in_data_format     │ TensixDataFormat.Float32 │ TensixDataFormat.Float32 │|  │ out_data_format         │ TensixDataFormat.Tf32 │ TensixDataFormat.Float16_b │   │ in_data_format     │ TensixDataFormat.Float32 │ TensixDataFormat.Float16_b │
> ```

@amahmudTT could you please share how you were able to get this information?

I assume you were able to pause execution before the operation starts via tt-exalens, but I don't know the steps. Would be useful knowledge to have.

**Comment by amahmudTT** [comment]
> > Found the reason for determinsitic part of pcc loss. The config registers are quite different for math and unpacker before the computation for transpose starts.
> > ```
> >   │ Format_SrcA       │ TensixDataFormat.Tf32    │                                                                                                          |  │ Format_SrcA       │ TensixDataFormat.Float16_b │
> >   │ Format_SrcB       │ TensixDataFormat.Tf32    │                                                                                                          |  │ Format_SrcB       │ TensixDataFormat.Float16_b │
> >   │ Format_Dstacc     │ TensixDataFormat.Float32 │                                                                                                          |  │ Format_Dstacc     │ TensixDataFormat.Float32   │
> >   │ Fp32_enabled      │ True                     │                                                                                                          |  │ Fp32_enabled      │ True                       │
> >   │ SFPU_Fp32_enabled │ True                     │                                                                                                          |  │ SFPU_Fp32_enabled │ True                       │
> >   │ INT8_math_enabled │ False                    │                                                                                                          |  │ INT8_math_enabled │ False                      │
> >   └───────────────────┴──────────────────────────┘                                                                                                          |  └───────────────────┴────────────────────────────┘
> >   UNPACKER                                                                                                                                                  |  UNPACKER
> >   ┌─────────────────────────┬───────────────────────┬───────────────────────┐   ┌────────────────────┬──────────────────────────┬──────────────────────────┐|  ┌─────────────────────────┬───────────────────────┬────────────────────────────┐   ┌────────────────────┬──────────────────────────┬────────────────────────────┐
> >   │ UNPACK CONFIG           │ REG_ID = 1            │ REG_ID = 2            │   │ TILE DESCRIPTOR    │ REG_ID = 1               │ REG_ID = 2               │|  │ UNPACK CONFIG           │ REG_ID = 1            │ REG_ID = 2                 │   │ TILE DESCRIPTOR    │ REG_ID = 1               │ REG_ID = 2                 │
> >   ├─────────────────────────┼───────────────────────┼───────────────────────┤   ├────────────────────┼──────────────────────────┼──────────────────────────┤|  ├─────────────────────────┼───────────────────────┼────────────────────────────┤   ├────────────────────┼──────────────────────────┼────────────────────────────┤
> >   │ out_data_format         │ TensixDataFormat.Tf32 │ TensixDataFormat.Tf32 │   │ in_data_format     │ TensixDataFormat.Float32 │ TensixDataFormat.Float32 │|  │ out_data_format         │ TensixDataFormat.Tf32 │ TensixDataFormat.Float16_b │   │ in_data_format     │ TensixDataFormat.Float32 │ TensixDataFormat.Float16_b │
> > ```
> 
> [@amahmudTT](https://github.com/amahmudTT) could you please share how you were able to get this information?
> 
> I assume you were able to pause execution before the operation starts via tt-exalens, but I don't know the steps. Would be useful knowledge to have.

You could use watcher pause or add this assembly instruction : asm volatile("break"). I think the assembly is much better and will preserve races more. For exalens I used.  dump-config-reg command.

**Comment by amahmudTT** [comment]
> Thanks for looking into this [@amahmudTT](https://github.com/amahmudTT)
> 
> [@amahmudTT](https://github.com/amahmudTT) [@nvelickovicTT](https://github.com/nvelickovicTT) this issue and issues like it have me worried about the init interface. It seems impossible for op kernel writers to find the right set of function calls + parameters to have correct output. We need a lot of support from the LLK team. That is slowing down both ops and llk teams. I hope this gets cleaned up with the API revamp and Quasar updates.

I made an issue for test-infra to test using the methodology I used for this. Yes we need to ramp up these tests, this month I have only been debugging things like these. The issue was not the combination, but the code in the combination. THe combination was correct.

**Comment by amahmudTT** [comment]
I put a comment in #27278 , I am not too hopeful the bugs are one and the same.  Since that bug seems to be a firmware or reader kernel problem. And this one is more like a compute kernel problem since it depends on initialization type. #27278 would manifest with a passthrough kernel , containing only wait_front and pop_front.

@bbradelTT @nvelickovicTT In light of this comment feel free to intervene and reprioritize.

**Comment by amahmudTT** [comment]
But regarding the deterministic loss in PCC due to buggy reconfigure function, Suresh found out that the other case where he lost PCC , it was fixed by the correct reconfiguring function 

https://github.com/tenstorrent/tt-llk/issues/615#issuecomment-3221978142

**Comment by amahmudTT** [comment]
https://github.com/tenstorrent/tt-metal/issues/27278 has been root caused, it is a runtime issue. (Tensor size not supported, but runtime was allowing them to be created, thus adding garbage data). 

I am back to this issue for finding the cause of non-deterministic PCC loss.

**Comment by rmillerTT** [comment]
@amahmudTT @bbradelTT  I am still seeing PCC issues with transpose_wh_init_short() even after incorporating this change. Below is what I'm observing:

Checkout:
tt-llk: rmillerTT/27493_transpose_dest_hang (has https://github.com/tenstorrent/tt-llk/pull/607 cherry-picked onto it)
tt-metal: rmillerTT/26077_welford_layernorm_infra

Run pytest:
pytest tests/ttnn/unit_tests/operations/fused/test_layer_norm.py::test_large_layer_norm_with_weight_bias_and_residual_input

This uses the full init, and PCC is >0.9999 for all 4 Welford's cases.

However, if you go to layernorm_large_tensor_welford.cpp and swap the transpose_wh_init() call with the (commented-out) transpose_wh_init_short(), the PCCs are:

0.9713
0.9737
0.9884
0.9843

This is certainly an improvement over the previous behavior (before the reconfig fix), where before PCC was in the range of ~0.5-0.75 and was unstable, but there is still a discrepancy between short init and full init.

**Comment by amahmudTT** [comment]
> [@amahmudTT](https://github.com/amahmudTT) [@bbradelTT](https://github.com/bbradelTT) I am still seeing PCC issues with transpose_wh_init_short() even after incorporating this change. Below is what I'm observing:
> 
> Checkout: tt-llk: rmillerTT/27493_transpose_dest_hang (has [tenstorrent/tt-llk#607](https://github.com/tenstorrent/tt-llk/pull/607) cherry-picked onto it) tt-metal: rmillerTT/26077_welford_layernorm_infra
> 
> Run pytest: pytest tests/ttnn/unit_tests/operations/fused/test_layer_norm.py::test_large_layer_norm_with_weight_bias_and_residual_input
> 
> This uses the full init, and PCC is >0.9999 for all 4 Welford's cases.
> 
> However, if you go to layernorm_large_tensor_welford.cpp and swap the transpose_wh_init() call with the (commented-out) transpose_wh_init_short(), the PCCs are:
> 
> 0.9713 0.9737 0.9884 0.9843
> 
> This is certainly an improvement over the previous behavior (before the reconfig fix), where before PCC was in the range of ~0.5-0.75 and was unstable, but there is still a discrepancy between short init and full init.

Yes this is something I mentioned in my previous comments, and this is the reason this issue has not been closed yet.

**Comment by rmillerTT** [comment]
Oof, sorry @amahmudTT ! Missed that. Thanks for looking into all this

**Comment by amahmudTT** [comment]
I think the issue is in the kernel and not in LLK.  

1.  Please do not ignore this comment of mine  https://github.com/tenstorrent/tt-metal/issues/27334#issuecomment-3216259747


2. This code has a weird way of using tile functions like tile_regs_acquire(), tile_regs_wait(), these two were put at the start of one loop and the counterparts under a different nested loop which may run more number of times, I think there is an imbalance regarding acquiring and releasing. Which is odd. Overall their ordering is very different from what I expect.

If I use this code 

```
                    if constexpr (SHORT) {
                        transpose_wh_init_short(cb_result_or_input);

                        MATH((llk_math_pack_sync_init<DST_ACCUM_MODE>()));
                        PACK((llk_pack_dest_init<DST_ACCUM_MODE, false>()));

                    } else {
                        transpose_wh_init(cb_result_or_input, cb_result_or_input);
                    }
```
The short init works just fine.  these do not decide on formatting or anything. One initializes the handshaking between math and pack thread related to how they are shared, the other decides from where packer will read. Thus I would recommend going over the kernel and fixing or checking these first before we look at it again.  And please do not forget point 1.

**Comment by amahmudTT** [comment]
My suggestion would be to go halfway through the code and output the result and match, while printing dest to make sure it is what we expeted there to be. I feel math is writing to wrong dest address or packer is reading from wrong dest address.

**Comment by amahmudTT** [comment]
I might have understood the error. The idea is probably do the welford algorithm and accumulate in the same places in destination register in dst_1 and dst_2, but if you take into account the bank flipping you are not accumulating in the same place and hence the result was fixed by the two lines of the full init 

```
                        MATH((llk_math_pack_sync_init<DST_ACCUM_MODE>()));
                        PACK((llk_pack_dest_init<DST_ACCUM_MODE, false>()));
```

To check the idea i made this change 

```
@@ -107,9 +109,6 @@ void MAIN {
     constexpr uint32_t dst2 = 2;

     for (uint32_t ncht = 0; ncht < NCHt; ncht++) {
-        tile_regs_acquire();
-        tile_regs_wait();
-
         // =====================================
         // First pass over the input.
         // Layernorm: Calculate E[x] and Var[x]
@@ -129,6 +128,8 @@ void MAIN {
                 // Go tile-by-tile in the block
                 for (uint32_t j = 0; j < blk; j++) {
                     if constexpr (fuse_pre_add) {
+                       tile_regs_acquire();
+                       tile_regs_wait();
                         // Fuse in = in + b in dst0
                         reconfig_data_format(cb_in, cb_inb);
                         add_tiles_init(cb_in, cb_inb);
@@ -142,10 +143,11 @@ void MAIN {
                         cb_push_back(cb_interm_pre_add, onetile);
                         cb_wait_front(cb_interm_pre_add, j + 1);
                         tile_regs_release();
-                        tile_regs_acquire();
-                        tile_regs_wait();
-                    }
+                   }

+                    tile_regs_acquire();
+                    tile_regs_wait();
+
                     add_trisc_nops<UNOPS, MNOPS, PNOPS, RISCV>();
                     // Transpose
                     // Note: The init_short should be sufficient here,
@@ -163,6 +165,10 @@ void MAIN {
                     welford_init();
                     welford(
                         dst0, dst1, dst2, /*start_N*/ (wt + j) * tile_width, /*end_N*/ W, /*last_run*/ wt + j == Wt);
+                   if(j < blk -1) {
+                    tile_regs_commit();
+                    tile_regs_release();
+                   }
                 }
```

And it give me the correct result. If my hypothesis is correct, then to deal with this properly, please 

1. Check out how the double buffering in dest register is implemented
2. Please do not start debugging after the full kernel is written, write partially test the results and then move on, which probably would have showed the mistake early on in this case.

My fix is a hacky fix, I think it could be optimized somewhat, may be you do not need to swith banks, and just do the welford in 1,2,3 instead of 0,1,2. But still the issue I mentioned that lowers the pcc in both full init and partial init with correct reconfiguring remains. It is upto you guys to remember the problem and fix it, since there is no separate issue and the algorithm is being changed too.

**Comment by amahmudTT** [comment]
But I still think you have imbalances in acquire/commit in this code , at least if it corresponds to the code before my change. 

            layernorm::compute::utils::transpose_pack_mean_and_variance(cb_ex, cb_ex2, dst1, dst2);

**Comment by amahmudTT** [comment]
On Second thoughts its probably related to not zeroing out, not accumulation, since tile_regs_release zeroes out the bank it worked on. Some part of the code is probably expecting zeroed out dest register, but not getting it.

**Comment by bbradelTT** [comment]
https://github.com/tenstorrent/tt-llk/pull/650 was reverted due to a tg quick llama hang and will need to be re-submitted after a fix

**Comment by bbradelTT** [comment]
PCC adjustments issues related to this issue:
- #28221 
- #28246 
- #28487

**Comment by amahmudTT** [comment]
I am working on other config related bugs. Since this bug has a workaround. I will fix those bugs first and come back to it.

**Comment by bbradelTT** [comment]
For https://github.com/tenstorrent/tt-metal/issues/28487
https://github.com/tenstorrent/tt-metal/actions/runs/17692061717/job/50291107814 shows
```
FAILED tests/nightly/single_card/stable_diffusion_xl_base/test_module_tt_crossattndownblock2d.py::test_crossattndown[device_params0-input_shape0-temb_shape0-encoder_shape0-640-10-640-1-0.997] - AssertionError: 0.9966914528606966
FAILED tests/nightly/single_card/stable_diffusion_xl_base/test_module_tt_crossattndownblock2d.py::test_crossattndown[device_params0-input_shape1-temb_shape1-encoder_shape1-1280-20-1280-2-0.995] - AssertionError: 0.9945725613050916
FAILED tests/nightly/single_card/stable_diffusion_xl_base/test_module_tt_transformerblock.py::test_transformerblock[device_params0-input_shape3-encoder_shape3-2-1-1280-20-1280-0.998] - AssertionError: 0.9979730925531584
FAILED tests/nightly/single_card/stable_diffusion_xl_base/test_module_tt_transformermodel.py::test_transformermodel[device_params0-input_shape1-encoder_shape1-2-1280-20-1280-0.996] - AssertionError: 0.9958844873260393
FAILED tests/nightly/single_card/stable_diffusion_xl_base/test_unet_loop.py::test_unet_loop[An astronaut riding a green horse-device_params0] - AssertionError: 0.8626947352583919
```

Focusing on the last one using comparison mode, test_unet_loop, the first pcc drop occurs, but then nothing else is affected:

<img width="1666" height="360" alt="Image" src="https://github.com/user-attachments/assets/6da6c42b-7a07-468e-a529-e5b66daa116e" />

Similarly, another such pcc drop pair:

<img width="1666" height="408" alt="Image" src="https://github.com/user-attachments/assets/5e6bad64-44ae-4797-9e1a-5bb8440bc022" />

First real difference starts with different golden comparisons, which is strange given I'm on the same commit
```

<img width="1666" height="408" alt="Image" src="https://github.com/user-attachments/assets/e95c7c68-634c-47d7-89e8-70be10a0c3e9" />

Results are using ipotkonjak/sdxl_comp_mode from @ipotkonjak-tt to avoid conv2d comparison issues.

Will continue investigation.

**Comment by bbradelTT** [comment]
Looking at the output of the unet test again, looks like there may be differences in div, multiply, sin, and cos. Not sure if that's due to golden functions, although may not be.

<img width="1861" height="804" alt="Image" src="https://github.com/user-attachments/assets/de9459ae-c41e-4dbf-af38-df3163a68ce1" />

**Comment by bbradelTT** [comment]
Re-ran with latest main. Nothing jumps out. pcc is slightly lower or higher:

<img width="1861" height="500" alt="Image" src="https://github.com/user-attachments/assets/9a14aeb0-3d8d-4c27-ab96-e56d8486f535" />

**Comment by bbradelTT** [comment]
I printed out the ULP for unet.
```
             _, pcc_message = comp_pcc(latents, torch_tt_latents, 0.8)
+            ulp_passed, ulp_message = comp_ulp(latents, torch_tt_latents, 1)
             logger.info(f"PCC of {i}. iteration is: {pcc_message}")
+            logger.info(f"ULP of {i}. iteration is: {ulp_message}")
```
 ULP is really high, and all over the place. The following is for the 10 iterations
```
Without Reconfig
1147081.0
192705.78125
280383.9375
266075.0625
737527.8125
7995200.0
4915002.0
646986.375
3047570.25
3506021.5
With Reconfig
1114313.0 - lower
239466.78125 - higher
499519.9375 - higher
229540.9375 - lower
606455.8125 - lower
13107008.0 - higher
6586170.0 - higher
614615.8125 - lower
864510.5 - lower
4652901.5 - higher
```

From everything I can tell, this is noise.

**Comment by bbradelTT** [comment]
This is blocking https://github.com/tenstorrent/tt-metal/issues/21482

**Comment by amahmudTT** [comment]
The galaxy tests passed with my changes when integrated into a latest branch. Indicating my PR was not the issue but it was just exposing some bug which either got resolved or got hidden. I currently made the PR again and am running galaxy tests again. 

Link to galaxy quick test running : https://github.com/tenstorrent/tt-metal/actions/runs/18484890956

**Comment by bbradelTT** [comment]
Investigation is completed. Updated SDXL PCCs can be retained. See https://github.com/tenstorrent/tt-metal/issues/28487 for details.

Closing.
