### ISSUE TITLE
Verify Fabric Tests for BH QB GE Metal Container

### ISSUE THREAD

**Issue by ejouretTT** [tenstorrent/tt-metal#28352]
Verify existing fabric tests and make sure they are functional for BH QB GE / make any changes/ add new features as required.

**Comment by williamlyTT** [comment]
Branch: `williamly/try-qb-ge`

Fabric system health tests non-deterministically fail with error
https://github.com/tenstorrent/tt-metal/actions/runs/18754837259/job/53522179682#step:6:89
```
C++ exception with description "unordered_map::at" thrown in the test body.
```

Fabric 2d tests failing test setup with router sync timeout
https://github.com/tenstorrent/tt-metal/actions/runs/18754837259/job/53522179731#step:6:355
```
unknown file: Failure
C++ exception with description "TT_THROW @ /work/tt_metal/impl/device/device_pool.cpp:664: tt::exception
info:
Fabric Router Sync: Timeout after 5000 ms. Device 0: Expected status 0xa2b2c2d2, got 0xa1b1c1d1
backtrace:
 --- /work/build/lib/libtt_metal.so(+0x459be3) [0x7fa11ac30be3]
 --- /work/build/lib/libtt_metal.so(+0x445a9c) [0x7fa11ac1ca9c]
 --- tt::DevicePool::wait_for_fabric_router_sync(unsigned int) const
 --- tt::tt_metal::distributed::MeshDevice::create_unit_meshes(std::vector<int, std::allocator<int> > const&, unsigned long, unsigned long, unsigned long, tt::tt_metal::DispatchCoreConfig const&, std::span<unsigned int const, 18446744073709551615ul>, unsigned long)
 --- ./build/test/tt_metal/tt_fabric/fabric_unit_tests(+0x2382fa) [0x55976e6122fa]
 --- void testing::internal::HandleExceptionsInMethodIfSupported<testing::TestSuite, void>(testing::TestSuite*, void (testing::TestSuite::*)(), char const*)
 --- testing::TestSuite::Run()
 --- testing::internal::UnitTestImpl::RunAllTests()
 --- bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
 --- testing::UnitTest::Run()
 --- ./build/test/tt_metal/tt_fabric/fabric_unit_tests(main+0x3e) [0x55976e65680e]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fa119d40d90]
 --- /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fa119d40e40]
 --- ./build/test/tt_metal/tt_fabric/fabric_unit_tests(_start+0x25) [0x55976e525595]
" thrown in SetUpTestSuite().
```

**Comment by williamlyTT** [comment]
Same failure as health tests seen in `FabricLiteBuild.BuildOnly` in cpp unit tests eth
https://github.com/tenstorrent/tt-metal/actions/runs/18754837259/job/53526323515#step:6:490
```
unknown file: Failure
C++ exception with description "unordered_map::at" thrown in the test body.
[  FAILED  ] FabricLiteBuild.BuildOnly (8935 ms)
```

**Comment by ejouretTT** [comment]
@ubcheema can you review this?

**Comment by williamlyTT** [comment]
I can provide access to a QBGE for debug: https://tenstorrent.atlassian.net/wiki/spaces/MI6/pages/1262944555/HowTo+Request+Access+to+Blackhole+GH+VLAN

Please send me your ssh public key after IT approves the request.

**Comment by williamlyTT** [comment]
@nhuang-tt should the `FabricLiteBuild` error go to you, does it need a separate issue?

**Comment by nhuang-tt** [comment]
Looking into FabricLiteBuild now

**Comment by nhuang-tt** [comment]
FabricLiteBuild nullptr should be fixed by https://github.com/tenstorrent/tt-metal/pull/31284

**Comment by ejouretTT** [comment]
@williamlyTT can you confirm if this is resolved?

**Comment by williamlyTT** [comment]
@ejouretTT still seeing the router sync error in Fabric2D tests

**Comment by ejouretTT** [comment]
@ubcheema @nhuang-tt for vis as this was issue caused it to be skipped in BH QB GE container^

**Comment by nhuang-tt** [comment]
Hi @ejouretTT , the issue I was looking at is Lite Fabric and that component is not related to Fabric

**Comment by ejouretTT** [comment]
ah that's totally clear and not confusing lmfao

**Comment by nnyamagoudar-TT** [comment]
For Fabric 2D tests, we have them running on CI on a branch as seen here: https://github.com/tenstorrent/tt-metal/actions/runs/18988494313, however there is a hang on the fabric stability tests that we are investigating right now

**Comment by williamlyTT** [comment]
Test no longer hangs after removing 1 warp cable on affected systems.
PR https://github.com/tenstorrent/tt-metal/pull/32398 re-enabled the disabled fabric tests in upstream container.
