### ISSUE TITLE
LLaMA Vision T3K garbage output

### ISSUE THREAD

**Issue by maksim-tsishkouski-epam** [tenstorrent/tt-metal#32284]
LLaMA Vision models "do not use image information" or hallucinating on T3K mesh (N300 works fine) while using `simple_vision_demo.py`.

On October 15, a [commit with switch tests from LLAMA_DIR to HF_MODEL](https://github.com/tenstorrent/tt-metal/commit/92bc5c3c9c2d735828c850e919ff71116dbf894a) was added.
Seems like it broke T3K 90B model but the issue with T3K 11B model existed before this switch.

T3K demo tests
1. 11B
    1. [N300 good run October 30](https://github.com/tenstorrent/tt-metal/actions/runs/18936263062/job/54064324384#step:6:211)
    2. [T3K bad same run October 30](https://github.com/tenstorrent/tt-metal/actions/runs/18936263062/job/54064324384#step:6:847) and the next lines
    3. [N300 good run before HF switch October 15](https://github.com/tenstorrent/tt-metal/actions/runs/18513809113/job/52760875593#step:9:388)
    4. [T3K bad same run before HF switch October 15](https://github.com/tenstorrent/tt-metal/actions/runs/18513809113/job/52760875593#step:9:1149) and the next lines
2. 90B
    1. [T3K bad run November 7](https://github.com/tenstorrent/tt-metal/actions/runs/19154083517/job/54752379570#step:6:222)
    2. [T3K good run before HF switch October 15](https://github.com/tenstorrent/tt-metal/actions/runs/18513809113/job/52760875536#step:9:387)

Maybe related to https://github.com/tenstorrent/tt-metal/issues/28635 and https://github.com/tenstorrent/tt-metal/issues/28442

**Comment by ekuslysTT** [comment]
@cglagovichTT who could look into this? CC @gwangTT

**Comment by gwangTT** [comment]
I believe this is addressed by @maksim-tsishkouski-epam 's PR -- https://github.com/tenstorrent/tt-metal/pull/32464.

**Comment by maksim-tsishkouski-epam** [comment]
> I believe this is addressed by @maksim-tsishkouski-epam 's PR -- https://github.com/tenstorrent/tt-metal/pull/32464.

No, that's a separate issue which I identified while working on the PR above. And the issue still exists (see examples from the recent run below)
[11B example](https://github.com/tenstorrent/tt-metal/actions/runs/19619672569/job/56177937223#step:6:1956)
[90B example](https://github.com/tenstorrent/tt-metal/actions/runs/19619672569/job/56177937220#step:6:220)

**Comment by gwangTT** [comment]
I see. Thanks, Maksim. We have plans to work on #28442, which could be related to this issue here as well. We can reevaluate once #28442 is fixed.

**Comment by uaydonat** [comment]
@gwangTT any update on this? is it fixed maybe?

**Comment by maksim-tsishkouski-epam** [comment]
[11B seems to be fine](https://github.com/tenstorrent/tt-metal/actions/runs/21121235351/job/60734626319#step:8:614)
[90B still "doesn't see the image"](https://github.com/tenstorrent/tt-metal/actions/runs/21121235351/job/60734626386#step:8:372)
```
<|begin_of_text|><|start_header_id|>user<|end_header_id|>

<|image|>Write a haiku for this image.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

I'd love to write a haiku, but I don't see an image. Can you please describe the image or provide a link to it? I'll do my best to craft a haiku that captures its essence.<|eot_id|>
```

**Comment by gwangTT** [comment]
> [11B seems to be fine](https://github.com/tenstorrent/tt-metal/actions/runs/21121235351/job/60734626319#step:8:614) [90B still "doesn't see the image"](https://github.com/tenstorrent/tt-metal/actions/runs/21121235351/job/60734626386#step:8:372)
> 
> ```
> <|begin_of_text|><|start_header_id|>user<|end_header_id|>
> 
> <|image|>Write a haiku for this image.<|eot_id|><|start_header_id|>assistant<|end_header_id|>
> 
> I'd love to write a haiku, but I don't see an image. Can you please describe the image or provide a link to it? I'll do my best to craft a haiku that captures its essence.<|eot_id|>
> ```

Interesting! Will take a look. Maybe @epam-ioannis-alexiou can help here as well.
