### ISSUE TITLE
ttnn.sinh operation fails with low PCC in most situations

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#8598]
**ttnn.sinh** operation fails with low PCC in all tested situations.

Problem is observed on both GS and WH cards.

**To Reproduce**
1. Checkout branch `ngrujic/op_bug_unit_tests` (soon to be merged into `main`).
4. Run unit test `test_eltwise_sinh.py ` using this command:
`pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_sinh.py`

**Expected behavior**
There are multiple test cases presented in the unit test, which are failing with low PCC.

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps and check the results. To do this you should:

1. Run non working sweep by using ` pytest tests/ttnn/python_api_testing/sweep_tests/run_sweep_test.py --input-path tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_sinh_test.yaml --input-method cli --cli-input results_ttnn_sinh`
3. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./results_ttnn_sinh).

**Comment by tt-aho** [comment]
I added mixed precision support to bcast on latest, so it should no longer crash.

**Comment by tt-aho** [comment]
Hey, that was my mistake. I added support for it in the op itself but forgot to remove the assert. Should be resolved on latest main a1b9781628e0275b18d960204d279166246c841e

**Comment by nemanjagrujic** [comment]
Hello @tt-aho, just rebased with latest main and rebuilt, but its still the same issue. Not sure what is happening. You can always test your self by running:

```
pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_sinh.py
``` 

To see if its fixed.

**Comment by nemanjagrujic** [comment]
Confirmed. Now only PCC is failing.

**Comment by KalaivaniMCW** [comment]
will be revisited after TTNN migration

**Comment by ruthreshx** [comment]
@nemanjagrujic error only occurs due to the exp op involves. Since exp has the low range support from TT end. Hence the test fails. I could see the test passes for the range (-88, 88) instead (-100, 100). Can we change the range for sinh op?

**Comment by nemanjagrujic** [comment]
> @nemanjagrujic error only occurs due to the exp op involves. Since exp has the low range support from TT end. Hence the test fails. I could see the test passes for the range (-88, 88) instead (-100, 100). Can we change the range for sinh op?

@ruthreshx Well, that's not a question for me. If there is valid range which is agreed on (and documented) we can change it in test.

**Comment by ruthreshx** [comment]
Hi @nemanjagrujic ,
Out of 30 collected test I could see 10 tests were passing for the range as (-88, 88).
I could see the issue been raising due to **[bfloat_8](https://github.com/tenstorrent/tt-metal/blob/c7a71d0dc880ccac23be99ffe73332b270796438/ttnn/cpp/ttnn/tensor/host_buffer/functions.hpp#L20)** and **[row_major](https://github.com/tenstorrent/tt-metal/blob/c7a71d0dc880ccac23be99ffe73332b270796438/ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_device_operation.cpp#L87)** is been restricted. Hence the tests fails.
Hence I made the condition to change those should be skipped from the test alone.

**Comment by ruthreshx** [comment]
yes @nemanjagrujic range has been documented it has already been skipped in test file itself.

**Comment by nemanjagrujic** [comment]
@ruthreshx OK, great

**Comment by VirdhatchaniKN** [comment]
Hi @nemanjagrujic 
Merged https://github.com/tenstorrent/tt-metal/pull/12056, can we close this issue?

**Comment by VirdhatchaniKN** [comment]
Closing issue
